#!/usr/bin/env python3
"""Build the load and rollback SQL for the Logica figure items.

Reads logica-figures.json and writes logica-figures-load.sql and
logica-figures-rollback.sql next to it. The load retires each seed_v1 text
item and inserts its figure version (same scale, facet, difficulty and option
text; new stem; figure; key and rationale where redesigned). Nothing is
deleted, so the text originals and their response history stay intact. It
refuses to run if any original's option text differs from the options_en the
figure was authored against.

    python3 scripts/sdc-hipo/build-logica-figures-sql.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
src = json.loads((HERE / "logica-figures.json").read_text(encoding="utf-8"))


def lit(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


ids = [it["replaces"] for it in src["items"]]
id_list = ", ".join(f"'{i}'::uuid" for i in ids)
rows = ",\n  ".join(
    "({}, {}, {}, {}, {}, {}::jsonb, {}::jsonb)".format(
        lit(it["replaces"]) + "::uuid",
        int(it["correct"]),
        lit(it.get("stem_en", src["stem_en"])),
        lit(it.get("stem_ar", src["stem_ar"])),
        lit(it.get("rationale")),
        lit(json.dumps(it["options_en"], ensure_ascii=False)),
        lit(json.dumps({**it["figure"], "replaces": it["replaces"]}, ensure_ascii=False, separators=(",", ":"))),
    )
    for it in src["items"]
)

load = f"""-- Logica items -> drawings, tables and charts (generated by build-logica-figures-sql.py; do not edit by hand).
-- Run once, after SME sign-off, in one transaction. Needs migration 00235.
BEGIN;

CREATE TEMP TABLE fig_load (replaces uuid PRIMARY KEY, correct int, stem_en text, stem_ar text, rationale text, options_en jsonb, figure jsonb) ON COMMIT DROP;
INSERT INTO fig_load VALUES
  {rows};

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items p JOIN fig_load d ON d.replaces = p.id
      WHERE p.status = 'in_review' AND p.figure IS NULL AND p.options_en = d.options_en) <> {len(ids)} THEN
    RAISE EXCEPTION 'expected {len(ids)} in_review text originals with unchanged option text';
  END IF;
  IF EXISTS (SELECT 1 FROM psy_items WHERE source = 'figure_v1') THEN
    RAISE EXCEPTION 'figure_v1 items already loaded';
  END IF;
END $$;

INSERT INTO psy_items (scale_id, kind, stem_en, stem_ar, options_en, options_ar, correct_index, reverse_keyed,
                       difficulty, status, source, facet, rationale, ar_reviewed, figure)
SELECT o.scale_id, o.kind, d.stem_en, d.stem_ar, o.options_en, o.options_ar, d.correct, o.reverse_keyed,
       o.difficulty, 'in_review', 'figure_v1', o.facet, coalesce(d.rationale, o.rationale), false, d.figure
FROM fig_load d JOIN psy_items o ON o.id = d.replaces;

UPDATE psy_items SET status = 'retired' WHERE id IN (SELECT replaces FROM fig_load);

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items WHERE source = 'figure_v1' AND status = 'in_review' AND figure IS NOT NULL) <> {len(ids)} THEN
    RAISE EXCEPTION 'insert count mismatch';
  END IF;
  IF EXISTS (SELECT 1 FROM psy_items p JOIN fig_load d ON d.replaces = p.id WHERE p.status <> 'retired') THEN
    RAISE EXCEPTION 'a replaced text item is still servable';
  END IF;
  IF (SELECT count(*) FROM psy_items WHERE facet IN ('ind_matrix', 'num_data') AND status IN ('approved', 'in_review') AND figure IS NULL) <> 0 THEN
    RAISE EXCEPTION 'a text matrix or data item is still servable';
  END IF;
END $$;

COMMIT;
"""

rollback = f"""-- Undo logica-figures-load.sql (generated; do not edit by hand).
-- Restores the text originals and retires the figure versions (kept, not
-- deleted, so any responses logged against them stay attributable).
BEGIN;
UPDATE psy_items SET status = 'retired' WHERE source = 'figure_v1';
UPDATE psy_items SET status = 'in_review' WHERE id IN ({id_list}) AND status = 'retired';
COMMIT;
"""

(HERE / "logica-figures-load.sql").write_text(load, encoding="utf-8")
(HERE / "logica-figures-rollback.sql").write_text(rollback, encoding="utf-8")
print("wrote logica-figures-load.sql and logica-figures-rollback.sql")
