#!/usr/bin/env python3
"""Build the load and rollback SQL for the Logica figure items.

Reads logica-figures.json and writes logica-figures-load.sql and
logica-figures-rollback.sql next to it.

- Replacement entries ('replaces'): the seed_v1 text item is retired and its
  figure version inserted (same scale, facet and option text; new stem;
  figure; key, difficulty and rationale where the entry changes them). The
  load refuses to run if any original's option text or difficulty differs
  from what the figure was authored against.
- New entries ('replaces' null): inserted alongside the bank, taking scale,
  facet and item kind from the item named in 'like'.

Nothing is deleted, so the text originals and their response history stay
intact.

    python3 scripts/sdc-hipo/build-logica-figures-sql.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
src = json.loads((HERE / "logica-figures.json").read_text(encoding="utf-8"))


def lit(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


def jlit(v):
    return lit(json.dumps(v, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def figure(it):
    tag = {"replaces": it["replaces"]} if it.get("replaces") else {"new": it["label"]}
    return jlit({**it["figure"], **tag})


repl = [it for it in src["items"] if it.get("replaces")]
new = [it for it in src["items"] if not it.get("replaces")]
total = len(repl) + len(new)

repl_rows = ",\n  ".join(
    "({}::uuid, {}, {}, {}, {}, {}, {}, {}, {})".format(
        lit(it["replaces"]),
        int(it["correct"]),
        lit(it["difficulty"]),
        lit(it.get("difficulty_from", it["difficulty"])),
        lit(it.get("stem_en", src["stem_en"])),
        lit(it.get("stem_ar", src["stem_ar"])),
        lit(it.get("rationale")),
        jlit(it["options_en"]),
        figure(it),
    )
    for it in repl
)

new_rows = ",\n  ".join(
    "({}::uuid, {}, {}, {}, {}, {}, {}, {}, {})".format(
        lit(it["like"]),
        int(it["correct"]),
        lit(it["difficulty"]),
        lit(it.get("stem_en", src["stem_en"])),
        lit(it.get("stem_ar", src["stem_ar"])),
        lit(it["rationale"]),
        jlit(it["options_en"]),
        jlit(it["options_ar"]),
        figure(it),
    )
    for it in new
)

load = f"""-- Logica items -> drawings, tables and charts (generated by build-logica-figures-sql.py; do not edit by hand).
-- Run once, after SME sign-off, in one transaction. Needs migration 00235.
-- {len(repl)} text items replaced by figure versions, {len(new)} new items added.
BEGIN;

CREATE TEMP TABLE fig_repl (replaces uuid PRIMARY KEY, correct int, difficulty text, difficulty_from text,
  stem_en text, stem_ar text, rationale text, options_en jsonb, figure jsonb) ON COMMIT DROP;
INSERT INTO fig_repl VALUES
  {repl_rows};

CREATE TEMP TABLE fig_new (like_id uuid, correct int, difficulty text, stem_en text, stem_ar text,
  rationale text, options_en jsonb, options_ar jsonb, figure jsonb) ON COMMIT DROP;
INSERT INTO fig_new VALUES
  {new_rows};

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items p JOIN fig_repl d ON d.replaces = p.id
      WHERE p.status = 'in_review' AND p.figure IS NULL AND p.options_en = d.options_en
        AND p.difficulty = d.difficulty_from) <> {len(repl)} THEN
    RAISE EXCEPTION 'expected {len(repl)} in_review text originals with unchanged option text and difficulty';
  END IF;
  IF (SELECT count(*) FROM fig_new n JOIN psy_items p ON p.id = n.like_id) <> {len(new)} THEN
    RAISE EXCEPTION 'a new item names a reference item that does not exist';
  END IF;
  IF EXISTS (SELECT 1 FROM psy_items WHERE source = 'figure_v1') THEN
    RAISE EXCEPTION 'figure_v1 items already loaded';
  END IF;
END $$;

INSERT INTO psy_items (scale_id, kind, stem_en, stem_ar, options_en, options_ar, correct_index, reverse_keyed,
                       difficulty, status, source, facet, rationale, ar_reviewed, figure)
SELECT o.scale_id, o.kind, d.stem_en, d.stem_ar, o.options_en, o.options_ar, d.correct, o.reverse_keyed,
       d.difficulty, 'in_review', 'figure_v1', o.facet, coalesce(d.rationale, o.rationale), false, d.figure
FROM fig_repl d JOIN psy_items o ON o.id = d.replaces;

INSERT INTO psy_items (scale_id, kind, stem_en, stem_ar, options_en, options_ar, correct_index, reverse_keyed,
                       difficulty, status, source, facet, rationale, ar_reviewed, figure)
SELECT r.scale_id, r.kind, n.stem_en, n.stem_ar, n.options_en, n.options_ar, n.correct, false,
       n.difficulty, 'in_review', 'figure_v1', r.facet, n.rationale, false, n.figure
FROM fig_new n JOIN psy_items r ON r.id = n.like_id;

UPDATE psy_items SET status = 'retired' WHERE id IN (SELECT replaces FROM fig_repl);

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items WHERE source = 'figure_v1' AND status = 'in_review' AND figure IS NOT NULL) <> {total} THEN
    RAISE EXCEPTION 'insert count mismatch';
  END IF;
  IF EXISTS (SELECT 1 FROM psy_items p JOIN fig_repl d ON d.replaces = p.id WHERE p.status <> 'retired') THEN
    RAISE EXCEPTION 'a replaced text item is still servable';
  END IF;
  IF (SELECT count(*) FROM psy_items WHERE facet IN ('ind_matrix', 'num_data') AND status IN ('approved', 'in_review') AND figure IS NULL) <> 0 THEN
    RAISE EXCEPTION 'a text matrix or data item is still servable';
  END IF;
END $$;

COMMIT;
"""

repl_ids = ", ".join(f"'{it['replaces']}'::uuid" for it in repl)
rollback = f"""-- Undo logica-figures-load.sql (generated; do not edit by hand).
-- Restores the text originals and retires the figure versions, including the
-- new items (kept, not deleted, so any responses logged against them stay
-- attributable).
BEGIN;
UPDATE psy_items SET status = 'retired' WHERE source = 'figure_v1';
UPDATE psy_items SET status = 'in_review' WHERE id IN ({repl_ids}) AND status = 'retired';
COMMIT;
"""

(HERE / "logica-figures-load.sql").write_text(load, encoding="utf-8")
(HERE / "logica-figures-rollback.sql").write_text(rollback, encoding="utf-8")
print(f"wrote logica-figures-load.sql ({len(repl)} replaced, {len(new)} new) and logica-figures-rollback.sql")
