"""Draft IDP development actions per SDC competency and target level (70/20/10).

DRAFTS for Ali AlShouli (SDC lead and subject-matter expert) to review or rewrite.
Module names and activities follow the SDC programme in proposal 20260809-SDC-02-HPHLD
(M1 Leading Self, M2 Leading Others, M3 Leading the Business, M4 Leading for the Future).
"""

MODULE = {"IN": "M3 Leading the Business", "RO": "M3 Leading the Business", "ECC": "M2 Leading Others",
          "PI": "M1 Leading Self", "AO": "M1 Leading Self", "SM": "M3 Leading the Business",
          "DSP": "M2 Leading Others", "EDP": "M3 Leading the Business", "IM": "M2 Leading Others",
          "LBE": "M4 Leading for the Future"}

EVIDENCE = "Examples of the goal behaviours, reviewed at each coaching touchpoint and in the post-programme assessment."

# ACTIONS[code][level] = (on the job 70%, coaching 20%, learning 10%)
ACTIONS = {
 "IN": {
  "Basic": ("Pick one task you repeat every week, list two ways to simplify it, try one and note the time saved.",
            "Discuss with your coach one improvement idea you hesitated to raise, and plan how to propose it.",
            "Module 3 session on innovation and problem solving; apply one idea-generation technique to a live task."),
  "Proficient": ("Lead a small improvement in your team's process: compare at least two options, pilot one for a month and measure the result.",
            "Review the pilot results with your coach, including what you would change and how you handled resistance.",
            "Module 3 innovation and problem-solving content; use the business challenge to test a new approach."),
  "Advanced": ("Sponsor a cross-department pilot linked to an SDC priority, with agreed success measures and a decision point to scale or stop.",
            "Work with your coach on building support for experimentation among senior stakeholders.",
            "Module 3 strategy and innovation sessions and the capstone project; share lessons with other departments."),
 },
 "RO": {
  "Basic": ("Agree three clear outcomes for the next quarter with your manager, track them weekly and flag any risk early.",
            "Review your weekly tracking with your coach and identify what most often delays your delivery.",
            "Module 1 goal-setting session; apply it to your own quarterly outcomes."),
  "Proficient": ("Own a team deliverable with competing priorities; set milestones, track progress and adjust the plan when obstacles appear.",
            "Use coaching to work through one trade-off between priorities and how you communicated it.",
            "Module 3 business acumen and decision-making sessions; apply one prioritisation tool to the deliverable."),
  "Advanced": ("Set a stretching outcome for a cross-team initiative, align resources around it and report progress to senior management monthly.",
            "Discuss with your coach how you sustain performance when conditions change mid-delivery.",
            "Module 3 and the capstone business project; present results and lessons in the C-suite presentation."),
 },
 "ECC": {
  "Basic": ("In your next three meetings, summarise what others said before giving your view, and share notes with colleagues afterwards.",
            "Ask your coach for feedback on how clearly you communicate in writing, using two recent emails.",
            "Module 2 communication and collaboration sessions; practise active listening in the workplace application."),
  "Proficient": ("Lead a joint task with another team: agree roles, hold regular check-ins and resolve one disagreement directly.",
            "Prepare with your coach for a conversation with a stakeholder who sees the work differently.",
            "Module 2 sessions on influence, feedback and collaboration; apply them to the team-based challenge."),
  "Advanced": ("Bring together stakeholders from several functions around a shared outcome, and run the forum that keeps them aligned.",
            "Use coaching to map key stakeholders and plan how to build trust where relationships are weak.",
            "Module 4 stakeholder management and Module 2 influence content; apply both in the capstone project."),
 },
 "PI": {
  "Basic": ("Review the policies that apply to your role with your manager and confirm how you handle confidential information.",
            "Discuss with your coach a time you made a mistake, how you acknowledged it and what you learned.",
            "Module 1 sessions on personal accountability and leadership standards."),
  "Proficient": ("When you see a practice that conflicts with policy or values, raise it constructively with the right person and record the outcome.",
            "Work through a real ethical dilemma from your role with your coach, weighing the competing interests.",
            "Module 1 leadership standards content; review SDC's code of conduct and its practical cases."),
  "Advanced": ("Act as the integrity reference point on a sensitive initiative, setting clear standards and holding others to them.",
            "Use coaching to prepare for addressing a complex ethical issue with senior stakeholders.",
            "Module 4 executive presence content; share an ethics case with the cohort."),
 },
 "AO": {
  "Basic": ("Keep a commitment log for one month: what you promised, when, and whether it was delivered; tell people early about any slip.",
            "Review the log with your coach and agree one habit that improves follow-through.",
            "Module 1 sessions on personal accountability and leadership mindset."),
  "Proficient": ("Take end-to-end ownership of one improvement, including follow-through after launch and correcting what does not work.",
            "Use coaching to plan the difficult conversations needed when commitments are at risk.",
            "Module 1 accountability content; apply it to your stretch assignment."),
  "Advanced": ("Define clear ownership for every outcome in a team or project, and review accountability openly at each milestone.",
            "Discuss with your coach how to hold others to account while keeping trust.",
            "Module 2 team leadership sessions; apply them in the team-based challenge."),
 },
 "SM": {
  "Basic": ("Read SDC's strategy and explain to your manager how your work contributes to two of its priorities.",
            "Discuss with your coach one decision where you considered the wider context, and what you would do differently.",
            "Module 3 strategy session and its pre-reading."),
  "Proficient": ("Lead a short horizon-scan of external trends affecting your area and present the implications to your department head.",
            "Pair with a senior sponsor to test the assumptions behind your department's plan.",
            "Module 3 strategy content and the business simulation."),
  "Advanced": ("Shape a two-to-three-year direction for your function, testing assumptions with scenarios and aligning stakeholders behind it.",
            "Use coaching to prepare how you will present and defend a long-term view to the executive team.",
            "Module 3 strategy content and the capstone project with its C-suite presentation."),
 },
 "DSP": {
  "Basic": ("Hold a monthly check-in with your team on commitments and standards, and remove one obstacle each month.",
            "Review with your coach how you balance short-term delivery with your team's workload.",
            "Module 2 team leadership sessions."),
  "Proficient": ("Set clear performance expectations for your team, review them with data each month and adjust resources where needed.",
            "Discuss with your coach a trade-off between short-term results and team capability, and how you decided.",
            "Module 2 performance and feedback content; Module 3 business acumen sessions."),
  "Advanced": ("Design a system that sustains performance in your area, such as a capability plan or a performance rhythm, and track its effect.",
            "Use coaching to plan deliberate trade-offs between results, people and risk.",
            "Module 3 business content and Module 4 succession readiness."),
 },
 "EDP": {
  "Basic": ("For your next three decisions, write down the information used, the options considered and a simple action plan.",
            "Review one of these decisions with your coach after it plays out.",
            "Module 3 decision-making session; apply one decision tool to a live choice."),
  "Proficient": ("Lead a decision that involves other stakeholders: evaluate alternatives and risks, decide on time and adjust the plan as conditions change.",
            "Use coaching to review how you balanced speed and evidence in that decision.",
            "Module 3 decision-making and problem-solving content and the business simulation."),
  "Advanced": ("Lead a high-impact decision under uncertainty, with a plan that sets priorities, contingencies and clear accountabilities.",
            "Discuss with your coach how you integrate conflicting views before deciding.",
            "Module 3 decision-making content and the capstone project."),
 },
 "IM": {
  "Basic": ("Recognise one specific contribution from a colleague each week, and explain how it helped the team's goal.",
            "Discuss with your coach what motivates the people you work with most closely.",
            "Module 2 sessions on team leadership and feedback."),
  "Proficient": ("In each team meeting, link current work to the team's purpose, and hold a development conversation with each team member this quarter.",
            "Use coaching to plan how to keep engagement up through a demanding period.",
            "Module 2 coaching and motivation content; apply it in the team-based challenge."),
  "Advanced": ("Lead your team or project through a significant change, communicating purpose and adapting your approach to different people's needs.",
            "Work with your coach on how you build confidence when the path is uncertain.",
            "Module 4 change management and executive presence content."),
 },
 "LBE": {
  "Basic": ("Choose two behaviours you expect of others and ask a trusted colleague to tell you monthly whether you show them consistently.",
            "Review that feedback with your coach and agree one change.",
            "Module 1 sessions on personal leadership and leadership standards."),
  "Proficient": ("Under pressure, model the standards you set: note one difficult moment each week and how your conduct reinforced them.",
            "Use coaching to reflect on composure under pressure and how others read your behaviour.",
            "Module 1 emotional intelligence content and Module 2 team leadership sessions."),
  "Advanced": ("Take visible responsibility for a difficult leadership decision, explain it openly and model the values it reflects.",
            "Discuss with your coach how your conduct sets the tone across the organisation.",
            "Module 4 executive presence content and the capstone presentation."),
 },
}

# Per Ali AlShouli's review (8 Oct 2026): each IDP priority carries a SMART goal, 30/60/90-day
# milestones and specific evidence of progress (completed outputs, documented decisions,
# manager feedback) rather than "observed behaviours". 70/20/10 is the development approach,
# not a scoring formula.
# PLAN[code][level] = (SMART goal, by day 30, by day 60, by day 90, evidence of progress)
PLAN = {
 "IN": {
  "Proficient": ("By day 90, pilot one improvement to a team process, chosen from at least two options, and show a measured gain in time, cost or quality.",
                 "Current process mapped; two improvement options compared and one agreed with the line manager.",
                 "Pilot running for at least four weeks, with a baseline and weekly measures.",
                 "Results reported to the team, with a decision to keep, change or stop the improvement.",
                 "Pilot plan and before/after measures; written decision on next steps; line manager feedback on the result."),
  "Advanced": ("By day 90, launch a cross-department pilot linked to an SDC priority, with agreed success measures and a scale-or-stop decision date.",
               "SDC priority and partner departments confirmed; success measures agreed with the sponsor.",
               "Pilot live in at least two departments; mid-point review held with stakeholders.",
               "Scale-or-stop recommendation presented to senior management.",
               "Pilot charter with success measures; mid-point review notes; senior management decision on the recommendation."),
 },
 "RO": {
  "Proficient": ("By day 90, deliver one team deliverable on time and to the agreed standard, with milestones tracked weekly and slippage flagged within one week.",
                 "Deliverable, standard and milestones agreed with the line manager; weekly tracker in use.",
                 "At least half the milestones met on time; any slippage raised with a recovery plan.",
                 "Deliverable completed and reviewed against the agreed standard.",
                 "Milestone tracker; completed deliverable; line manager's written assessment against the standard."),
  "Advanced": ("By day 90, lead a cross-team initiative to a stretching, measurable outcome, reporting progress to senior management every month.",
               "Outcome and measures agreed with the sponsor; resources and owners assigned across teams.",
               "First two monthly progress reports issued; at least one course correction documented.",
               "Outcome achieved or a documented recovery plan approved by the sponsor.",
               "Monthly progress reports; documented course corrections; sponsor feedback on the outcome achieved."),
 },
 "ECC": {
  "Proficient": ("By day 90, complete a joint task with another team with roles agreed in writing, fortnightly check-ins and at least one disagreement resolved directly.",
                 "Joint task, roles and check-in rhythm agreed with the other team in writing.",
                 "At least three check-ins held; one disagreement raised and resolved, with the outcome recorded.",
                 "Joint task delivered; both teams give feedback on the collaboration.",
                 "Written role agreement; check-in notes; feedback from the other team's lead and the line manager."),
  "Advanced": ("By day 90, set up and chair a cross-functional forum around a shared outcome, with agreed actions tracked between meetings.",
               "Stakeholder map completed; forum purpose and members agreed with the sponsor.",
               "At least two forum meetings held, with actions and owners recorded.",
               "Shared outcome progressed as agreed; members rate the forum's usefulness.",
               "Stakeholder map; forum action log; stakeholder feedback collected at day 90."),
 },
 "PI": {
  "Proficient": ("By day 90, raise at least one practice that conflicts with policy or values through the right channel, and record the outcome.",
                 "Policies and code of conduct relevant to the role reviewed with the line manager.",
                 "One real dilemma worked through with the coach, with the reasoning written down.",
                 "Issue raised constructively through the right channel; outcome recorded.",
                 "Written dilemma analysis; record of the issue raised and its outcome; line manager feedback on how it was handled."),
  "Advanced": ("By day 90, set and communicate clear integrity standards for one sensitive initiative and review compliance with them at each milestone.",
               "Standards for the initiative written and agreed with the sponsor.",
               "Standards communicated to everyone involved; first compliance review held.",
               "Second review completed; any breaches addressed and lessons shared.",
               "Written standards; compliance review notes; sponsor feedback on how issues were handled."),
 },
 "AO": {
  "Proficient": ("By day 90, own one improvement end to end, including follow-through after launch and correction of anything that does not work.",
                 "Improvement scope, owner role and success measures agreed with the line manager.",
                 "Improvement launched; first follow-up review completed.",
                 "Issues found after launch corrected; results reported.",
                 "Improvement plan and measures; follow-up review notes; line manager feedback on ownership and follow-through."),
  "Advanced": ("By day 90, assign a named owner to every outcome in a team or project and review accountability openly at each milestone.",
               "Ownership map for all outcomes agreed with the team.",
               "First accountability review held; slipped commitments addressed directly.",
               "Second review held; on-time delivery compared with the start.",
               "Ownership map; accountability review notes; team and sponsor feedback."),
 },
 "SM": {
  "Basic": ("By day 90, explain in writing how your work contributes to two SDC strategic priorities, and adjust one piece of work to fit them better.",
            "SDC strategy read and discussed with the line manager.",
            "One-page note linking your work to two priorities, reviewed with the coach.",
            "One piece of work adjusted, and the change explained to the line manager.",
            "One-page note; the adjusted piece of work; line manager feedback on the link to strategy."),
  "Proficient": ("By day 90, complete a horizon scan of external trends affecting your area and present the implications to your department head.",
                 "Scope of the scan and its sources agreed with the department head.",
                 "Trends analysed and implications drafted; assumptions tested with a senior sponsor.",
                 "Findings presented; at least one implication taken into the department plan.",
                 "Horizon-scan report; presentation; department head's decision on the recommendations."),
  "Advanced": ("By day 90, draft a two-to-three-year direction for your function, tested with scenarios and reviewed by the executive team.",
               "Key assumptions and scenarios defined with the coach and a sponsor.",
               "Draft direction shared with the main stakeholders and their input recorded.",
               "Direction presented to the executive team and their decision recorded.",
               "Scenario analysis; draft direction paper; executive team feedback and decision."),
 },
 "DSP": {
  "Basic": ("By day 90, hold a monthly check-in with your team on commitments and standards, and remove at least one obstacle each month.",
            "First check-in held; commitments and standards written down.",
            "Second check-in held; two obstacles removed and recorded.",
            "Third check-in held; team feedback gathered on workload and support.",
            "Check-in notes; log of obstacles removed; team feedback."),
  "Proficient": ("By day 90, set written performance expectations for your team and review them with data every month, adjusting resources where needed.",
                 "Expectations and measures written and agreed with each team member.",
                 "First monthly data review held; at least one resource adjustment made.",
                 "Second review held; changes in team performance reported.",
                 "Written expectations; monthly performance data; line manager feedback on the team's results."),
  "Advanced": ("By day 90, put in place one system that sustains performance in your area, such as a capability plan or performance rhythm, and track its effect.",
               "Performance risk identified and the system designed with the sponsor.",
               "System in use; first measures collected.",
               "Effect reviewed and reported, with the trade-offs made documented.",
               "System design; performance measures before and after; sponsor feedback."),
 },
 "EDP": {
  "Basic": ("By day 90, document your next three decisions (information used, options considered, action plan) and review the outcome of each.",
            "First decision documented using a simple template.",
            "Second and third decisions documented; first one reviewed after it played out.",
            "All three reviewed with the coach; one lesson applied.",
            "Three decision records; post-decision reviews; line manager feedback on decision quality."),
  "Proficient": ("By day 90, lead one decision involving other stakeholders, with alternatives and risks evaluated in writing and the decision made by the agreed date.",
                 "Decision, deadline and stakeholders agreed with the line manager.",
                 "Options and risks analysed in writing; stakeholders consulted.",
                 "Decision made on time; the plan adjusted as conditions changed, and the result reviewed.",
                 "Decision paper with options and risks; record of stakeholder input; line manager feedback on the decision and its timing."),
  "Advanced": ("By day 90, lead a high-impact decision under uncertainty with a written plan setting priorities, contingencies and accountabilities.",
               "Decision framed with the sponsor; conflicting views gathered.",
               "Decision made and the plan issued with contingencies and owners.",
               "First results reviewed; contingencies used or adjusted as needed.",
               "Decision paper; implementation plan; sponsor review of the outcome."),
 },
 "IM": {
  "Basic": ("By day 90, give specific recognition at least once a week, each time linking the contribution to a team goal.",
            "Recognition habit started; motivators of close colleagues discussed with the coach.",
            "At least eight recognitions given and noted.",
            "Feedback gathered from colleagues on the effect.",
            "Recognition log; colleague feedback; coach review."),
  "Proficient": ("By day 90, hold a development conversation with every team member and link current work to the team's purpose in each team meeting.",
                 "Development conversations scheduled; team purpose agreed and written down.",
                 "At least half the conversations held, each with an agreed action.",
                 "All conversations held; team engagement check completed.",
                 "Record of conversations and agreed actions; short team engagement check; line manager feedback."),
  "Advanced": ("By day 90, lead your team or project through a significant change with a written communication plan and two engagement checks.",
               "Change and its purpose defined; communication plan written.",
               "Change under way; first engagement check done and concerns addressed.",
               "Change milestones met; second engagement check compared with the first.",
               "Communication plan; two engagement checks; sponsor feedback on how the change was led."),
 },
 "LBE": {
  "Basic": ("By day 90, choose two behaviours you expect of others and get monthly feedback from a trusted colleague on whether you show them consistently.",
            "Two behaviours chosen; colleague agreed to give feedback.",
            "Two rounds of feedback received; one change agreed with the coach.",
            "Third round of feedback shows the change in place.",
            "Monthly feedback notes; agreed change; colleague and line manager feedback."),
  "Proficient": ("By day 90, keep a weekly record of one high-pressure moment and how your conduct reinforced the standards you set, and seek team feedback.",
                 "Standards written down; weekly record started.",
                 "Record reviewed with the coach; one pattern identified and addressed.",
                 "Team feedback gathered on consistency under pressure.",
                 "Weekly record; coach review notes; team feedback."),
  "Advanced": ("By day 90, take visible responsibility for one difficult leadership decision, explaining it openly and showing the values it reflects.",
               "Decision identified and the communication approach planned with the coach.",
               "Decision communicated openly; questions and concerns answered.",
               "Follow-up held on the decision's effect; lessons shared with peers.",
               "Communication record; follow-up notes; senior stakeholder feedback."),
 },
}
