-- Logica matrix items -> drawn figures (generated by build-logica-figures-sql.py; do not edit by hand).
-- Run once, after SME sign-off, in one transaction. Needs migration 00235.
BEGIN;

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items WHERE id IN ('1c5a49ec-aa6a-4f30-a663-60b00cc90c5d'::uuid, '9f631041-3fb6-463f-a979-39cec64cbd1b'::uuid, 'ef2960dc-a122-4321-9bdc-be21cbe6c4ca'::uuid, '5b06229e-46f7-42df-9e01-0cd37b3dd002'::uuid, 'cd15e7c9-9f40-4f43-9d44-d95945752a1a'::uuid, 'eed66f1e-c04c-4980-9ae9-31a78494b63d'::uuid, '5d6ea32f-dda6-4d01-9b30-f4e1b257f5ee'::uuid, '8fa1a761-4b01-4fc0-879e-fba14a6cc75a'::uuid, 'f1f8fe62-7e7d-4e20-9d5f-4bbe2614b334'::uuid, 'f9ec2980-6227-4aa9-8f7b-7d6eed3b29d2'::uuid) AND status = 'in_review' AND facet = 'ind_matrix' AND figure IS NULL) <> 10 THEN
    RAISE EXCEPTION 'expected 10 in_review ind_matrix text originals';
  END IF;
  IF EXISTS (SELECT 1 FROM psy_items WHERE source = 'figure_v1') THEN
    RAISE EXCEPTION 'figure_v1 items already loaded';
  END IF;
END $$;

INSERT INTO psy_items (scale_id, kind, stem_en, stem_ar, options_en, options_ar, correct_index, reverse_keyed,
                       difficulty, status, source, facet, rationale, ar_reviewed, figure)
SELECT o.scale_id, o.kind, 'Look at the pattern in the grid. Which option belongs in the empty cell?', 'انظر إلى النمط في الشبكة. أيّ خيار يناسب الخانة الفارغة؟', o.options_en, o.options_ar, d.correct, o.reverse_keyed,
       o.difficulty, 'in_review', 'figure_v1', o.facet, coalesce(d.rationale, o.rationale), false, d.figure
FROM (VALUES
  ('1c5a49ec-aa6a-4f30-a663-60b00cc90c5d'::uuid, 0, NULL, '{"cols":2,"cells":[{"arrow":"up"},{"arrow":"right"},{"arrow":"down"},null],"options":[{"arrow":"left"},{"arrow":"up"},{"arrow":"down"},{"arrow":"right"}],"replaces":"1c5a49ec-aa6a-4f30-a663-60b00cc90c5d"}'::jsonb),
  ('9f631041-3fb6-463f-a979-39cec64cbd1b'::uuid, 2, 'Every row and every column holds a white circle, a half-shaded circle and a fully shaded circle once each. Row 3 already has full and white, so the missing cell is the half-shaded circle; the third column (full, white, ?) confirms it. ''Fully white'' and ''fully shaded'' repeat a state already in the row. ''Right half shaded'' never appears in the grid.', '{"cols":3,"cells":[{"shape":"circle","fill":"none"},{"shape":"circle","fill":"left"},{"shape":"circle","fill":"full"},{"shape":"circle","fill":"left"},{"shape":"circle","fill":"full"},{"shape":"circle","fill":"none"},{"shape":"circle","fill":"full"},{"shape":"circle","fill":"none"},null],"options":[{"shape":"circle","fill":"none"},{"shape":"circle","fill":"full"},{"shape":"circle","fill":"left"},{"shape":"circle","fill":"right"}],"replaces":"9f631041-3fb6-463f-a979-39cec64cbd1b"}'::jsonb),
  ('ef2960dc-a122-4321-9bdc-be21cbe6c4ca'::uuid, 0, NULL, '{"cols":2,"cells":[{"dots":1},{"dots":2},{"dots":3},null],"options":[{"dots":4},{"dots":3},{"dots":2},{"dots":5}],"replaces":"ef2960dc-a122-4321-9bdc-be21cbe6c4ca"}'::jsonb),
  ('5b06229e-46f7-42df-9e01-0cd37b3dd002'::uuid, 0, NULL, '{"cols":3,"cells":[{"shape":"circle","side":{"count":1}},{"shape":"square","side":{"count":2}},{"shape":"triangle","side":{"count":3}},{"shape":"square","side":{"count":3}},{"shape":"triangle","side":{"count":1}},{"shape":"circle","side":{"count":2}},{"shape":"triangle","side":{"count":2}},{"shape":"circle","side":{"count":3}},null],"options":[{"shape":"square","side":{"count":1}},{"shape":"triangle","side":{"count":1}},{"shape":"square","side":{"count":3}},{"shape":"circle","side":{"count":1}}],"replaces":"5b06229e-46f7-42df-9e01-0cd37b3dd002"}'::jsonb),
  ('cd15e7c9-9f40-4f43-9d44-d95945752a1a'::uuid, 0, 'Along every row one more small cell is shaded at each step. Row 1 shows the order the cells fill in: top-left, top-right, then bottom-right, then bottom-left (clockwise). Row 3 has top-left, then top-left and top-right, so the next step adds bottom-right. The option ending in bottom-left goes counter-clockwise. ''Two shaded'' fails to add a cell. ''Four shaded'' adds two cells at once.', '{"cols":3,"cells":[{"quad":["tl","tr"]},{"quad":["tl","tr","br"]},{"quad":["tl","tr","br","bl"]},{"quad":[]},{"quad":["tl"]},{"quad":["tl","tr"]},{"quad":["tl"]},{"quad":["tl","tr"]},null],"options":[{"quad":["tl","tr","br"]},{"quad":["tl","tr","bl"]},{"quad":["tl","br"]},{"quad":["tl","tr","br","bl"]}],"replaces":"cd15e7c9-9f40-4f43-9d44-d95945752a1a"}'::jsonb),
  ('eed66f1e-c04c-4980-9ae9-31a78494b63d'::uuid, 0, NULL, '{"cols":3,"cells":[{"lines":1},{"lines":2},{"lines":3},{"lines":2},{"lines":3},{"lines":4},{"lines":3},{"lines":4},null],"options":[{"lines":5},{"lines":4},{"lines":6},{"lines":3}],"replaces":"eed66f1e-c04c-4980-9ae9-31a78494b63d"}'::jsonb),
  ('5d6ea32f-dda6-4d01-9b30-f4e1b257f5ee'::uuid, 0, NULL, '{"cols":2,"cells":[{"clock":12},{"clock":3},{"clock":6},null],"options":[{"clock":9},{"clock":12},{"clock":3},{"clock":6}],"replaces":"5d6ea32f-dda6-4d01-9b30-f4e1b257f5ee"}'::jsonb),
  ('8fa1a761-4b01-4fc0-879e-fba14a6cc75a'::uuid, 0, NULL, '{"cols":2,"cells":[{"shape":"circle","inner":{"glyph":"dot","count":1}},{"shape":"circle"},{"shape":"triangle","inner":{"glyph":"dot","count":1}},null],"options":[{"shape":"triangle"},{"shape":"triangle","inner":{"glyph":"dot","count":1}},{"shape":"circle"},{"shape":"square"}],"replaces":"8fa1a761-4b01-4fc0-879e-fba14a6cc75a"}'::jsonb),
  ('f1f8fe62-7e7d-4e20-9d5f-4bbe2614b334'::uuid, 0, NULL, '{"cols":2,"cells":[{"shape":"square","size":"small"},{"shape":"square","size":"large"},{"shape":"triangle","size":"small"},null],"options":[{"shape":"triangle","size":"large"},{"shape":"triangle","size":"small"},{"shape":"square","size":"large"},{"shape":"square","size":"small"}],"replaces":"f1f8fe62-7e7d-4e20-9d5f-4bbe2614b334"}'::jsonb),
  ('f9ec2980-6227-4aa9-8f7b-7d6eed3b29d2'::uuid, 0, NULL, '{"cols":2,"cells":[{"shape":"circle","inner":{"glyph":"star","count":1}},{"shape":"circle","inner":{"glyph":"star","count":2}},{"shape":"square","inner":{"glyph":"star","count":1}},null],"options":[{"shape":"square","inner":{"glyph":"star","count":2}},{"shape":"circle","inner":{"glyph":"star","count":2}},{"shape":"square","inner":{"glyph":"star","count":1}},{"shape":"square","inner":{"glyph":"star","count":3}}],"replaces":"f9ec2980-6227-4aa9-8f7b-7d6eed3b29d2"}'::jsonb)
) AS d(replaces, correct, rationale, figure)
JOIN psy_items o ON o.id = d.replaces;

UPDATE psy_items SET status = 'retired' WHERE id IN ('1c5a49ec-aa6a-4f30-a663-60b00cc90c5d'::uuid, '9f631041-3fb6-463f-a979-39cec64cbd1b'::uuid, 'ef2960dc-a122-4321-9bdc-be21cbe6c4ca'::uuid, '5b06229e-46f7-42df-9e01-0cd37b3dd002'::uuid, 'cd15e7c9-9f40-4f43-9d44-d95945752a1a'::uuid, 'eed66f1e-c04c-4980-9ae9-31a78494b63d'::uuid, '5d6ea32f-dda6-4d01-9b30-f4e1b257f5ee'::uuid, '8fa1a761-4b01-4fc0-879e-fba14a6cc75a'::uuid, 'f1f8fe62-7e7d-4e20-9d5f-4bbe2614b334'::uuid, 'f9ec2980-6227-4aa9-8f7b-7d6eed3b29d2'::uuid);

DO $$
BEGIN
  IF (SELECT count(*) FROM psy_items WHERE source = 'figure_v1' AND status = 'in_review' AND figure IS NOT NULL) <> 10 THEN
    RAISE EXCEPTION 'insert count mismatch';
  END IF;
  IF (SELECT count(*) FROM psy_items WHERE facet = 'ind_matrix' AND status IN ('approved', 'in_review') AND figure IS NULL) <> 0 THEN
    RAISE EXCEPTION 'a text matrix item is still servable';
  END IF;
END $$;

COMMIT;
