// AUTO-GENERATED - do not hand-edit. VIFM Cognitive Item-Bank Standard v1 seed.
// 120 vetted items (4 subtests x 3 facets x 10 = 3 easy / 4 medium / 3 hard per
// facet), authored to blueprint then adversarially construct-reviewed (neutral
// content, no Verbal<->Deductive leaks, single defensible key). Arabic is
// machine-drafted MSA - loaded with ar_reviewed=false pending a human pass.
// Loaded by seedCognitiveBankAction as approved items, source='seed_v1'.

export type CognitiveSeedItem = {
  subtest: string;
  facet: string;
  difficulty: "easy" | "medium" | "hard";
  stem_en: string;
  options_en: string[];
  correct_index: number;
  stem_ar: string;
  options_ar: string[];
  rationale_en: string;
};

export const COGNITIVE_SEED_V1: CognitiveSeedItem[] = [
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "easy",
    stem_en: "If 3 identical crates weigh 12 kg in total, how much do 5 of the same crates weigh?",
    options_en: ["18 kg", "20 kg", "15 kg", "24 kg"], correct_index: 1,
    stem_ar: "إذا كانت 3 صناديق متطابقة تزن 12 كجم في المجموع، فكم تزن 5 صناديق من النوع نفسه؟",
    options_ar: ["18 كجم", "20 كجم", "15 كجم", "24 كجم"],
    rationale_en: "Each crate weighs 12 / 3 = 4 kg, so 5 crates weigh 5 x 4 = 20 kg (key, index 1). 18 kg (index 0) wrongly uses 6 kg per crate. 15 kg (index 2) uses 3 kg per crate. 24 kg (index 3) doubles the original total instead of scaling from 3 to 5.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "easy",
    stem_en: "A recipe uses 2 cups of flour for every 3 cups of water. If you use 6 cups of flour, how many cups of water are needed?",
    options_en: ["9", "6", "12", "4"], correct_index: 0,
    stem_ar: "تستخدم وصفة كوبين من الطحين مقابل كل 3 أكواب من الماء. إذا استخدمت 6 أكواب من الطحين، فكم كوبًا من الماء يلزم؟",
    options_ar: ["9", "6", "12", "4"],
    rationale_en: "Flour scales from 2 to 6, a factor of 3, so water scales the same way: 3 x 3 = 9 cups (key, index 0). 6 (index 1) just copies the flour amount. 12 (index 2) doubles 6 instead of using the ratio. 4 (index 3) subtracts rather than scales.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "easy",
    stem_en: "A car travels 60 km in 1 hour at a steady speed. How far does it travel in 3 hours at the same speed?",
    options_en: ["120 km", "180 km", "90 km", "200 km"], correct_index: 1,
    stem_ar: "تقطع سيارة 60 كم في ساعة واحدة بسرعة ثابتة. كم مسافة تقطع في 3 ساعات بالسرعة نفسها؟",
    options_ar: ["120 كم", "180 كم", "90 كم", "200 كم"],
    rationale_en: "At 60 km per hour, 3 hours gives 60 x 3 = 180 km (key, index 1). 120 km (index 0) only counts 2 hours. 90 km (index 2) adds half again instead of tripling. 200 km (index 3) is a rounded guess not tied to the rate.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "medium",
    stem_en: "5 identical pens cost 40 coins. How much do 8 of the same pens cost?",
    options_en: ["56 coins", "64 coins", "60 coins", "72 coins"], correct_index: 1,
    stem_ar: "خمسة أقلام متطابقة تكلف 40 قطعة نقدية. فكم تكلف 8 أقلام من النوع نفسه؟",
    options_ar: ["56 قطعة", "64 قطعة", "60 قطعة", "72 قطعة"],
    rationale_en: "One pen costs 40 / 5 = 8 coins, so 8 pens cost 8 x 8 = 64 coins (key, index 1). 56 coins (index 0) uses 7 pens by mistake. 60 coins (index 2) wrongly assumes a round number. 72 coins (index 3) uses 9 pens instead of 8.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "medium",
    stem_en: "A map uses a scale where 2 cm represents 5 km. Two towns are 14 cm apart on the map. What is the real distance between them?",
    options_en: ["28 km", "35 km", "30 km", "40 km"], correct_index: 1,
    stem_ar: "تستخدم خريطة مقياسًا حيث يمثل كل 2 سم مسافة 5 كم. تبعد بلدتان 14 سم على الخريطة. فما المسافة الحقيقية بينهما؟",
    options_ar: ["28 كم", "35 كم", "30 كم", "40 كم"],
    rationale_en: "14 cm is 7 groups of 2 cm, and each group is 5 km, so 7 x 5 = 35 km (key, index 1). 28 km (index 0) doubles 14 as if 1 cm equaled 2 km. 30 km (index 2) is a rounding guess. 40 km (index 3) wrongly treats each cm as roughly 3 km.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "medium",
    stem_en: "In a garden the ratio of roses to tulips is 4 to 7. If there are 28 tulips, how many roses are there?",
    options_en: ["16", "12", "20", "14"], correct_index: 0,
    stem_ar: "في حديقة، نسبة الورود إلى زهور التوليب هي 4 إلى 7. إذا كان هناك 28 زهرة توليب، فكم عدد الورود؟",
    options_ar: ["16", "12", "20", "14"],
    rationale_en: "Tulips scale from 7 to 28, a factor of 4, so roses scale the same: 4 x 4 = 16 (key, index 0). 12 (index 1) uses a factor of 3. 20 (index 2) uses a factor of 5. 14 (index 3) just halves the tulip count, ignoring the ratio.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "medium",
    stem_en: "4 workers can pack 24 boxes in an hour, all working at the same steady rate. How many boxes can 6 workers pack in an hour?",
    options_en: ["30", "36", "32", "48"], correct_index: 1,
    stem_ar: "يستطيع 4 عمال تعبئة 24 صندوقًا في ساعة، ويعمل الجميع بالمعدل الثابت نفسه. فكم صندوقًا يستطيع 6 عمال تعبئتها في ساعة؟",
    options_ar: ["30", "36", "32", "48"],
    rationale_en: "Each worker packs 24 / 4 = 6 boxes per hour, so 6 workers pack 6 x 6 = 36 (key, index 1). 30 (index 0) uses only 5 workers. 32 (index 2) adds 8 for 2 extra workers at the wrong rate. 48 (index 3) doubles the total as if workers doubled from 4 to 8.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "hard",
    stem_en: "A tap fills a container at a steady rate, pouring 9 litres every 6 minutes. How many litres does it pour in 10 minutes?",
    options_en: ["13.5 litres", "15 litres", "16 litres", "12 litres"], correct_index: 0,
    stem_ar: "يملأ صنبور وعاءً بمعدل ثابت، فيصب 9 لترات كل 6 دقائق. فكم لترًا يصب في 10 دقائق؟",
    options_ar: ["13.5 لتر", "15 لتر", "16 لتر", "12 لتر"],
    rationale_en: "The rate is 9 / 6 = 1.5 litres per minute, so 10 minutes gives 1.5 x 10 = 13.5 litres (key, index 0). 15 litres (index 1) rounds the answer up to a whole number. 16 litres (index 2) overestimates the rate. 12 litres (index 3) uses 8 minutes or a rate of 1.2 by mistake.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "hard",
    stem_en: "Two ropes are cut in the ratio 3 to 5. The longer piece is 40 cm longer than the shorter piece. What is the length of the shorter piece?",
    options_en: ["60 cm", "48 cm", "100 cm", "24 cm"], correct_index: 0,
    stem_ar: "يُقطع حبلان بنسبة 3 إلى 5. القطعة الأطول تزيد عن القطعة الأقصر بمقدار 40 سم. فما طول القطعة الأقصر؟",
    options_ar: ["60 سم", "48 سم", "100 سم", "24 سم"],
    rationale_en: "The difference is 5 - 3 = 2 ratio parts, which equal 40 cm, so 1 part is 20 cm. The shorter piece is 3 parts: 3 x 20 = 60 cm (key, index 0). 48 cm (index 1) mishandles the part size. 100 cm (index 2) is the longer piece (5 parts), not the shorter. 24 cm (index 3) treats each part as 8 cm by dividing 40 by 5.",
  },
  {
    subtest: "numerical", facet: "num_ratio", difficulty: "hard",
    stem_en: "8 identical machines finish a job in 15 hours, all running at the same steady rate. How long would 10 such machines take to finish the same job?",
    options_en: ["12 hours", "18 hours", "13 hours", "19 hours"], correct_index: 0,
    stem_ar: "تُنجز 8 آلات متطابقة عملًا في 15 ساعة، وتعمل جميعها بالمعدل الثابت نفسه. فكم من الوقت تستغرق 10 آلات مماثلة لإنجاز العمل نفسه؟",
    options_ar: ["12 ساعة", "18 ساعة", "13 ساعة", "19 ساعة"],
    rationale_en: "The total work is 8 x 15 = 120 machine-hours. With 10 machines the time is 120 / 10 = 12 hours (key, index 0). This is inverse proportion: more machines means less time. 18 hours (index 1) scales the wrong way. 13 hours (index 2) subtracts a small amount arbitrarily. 19 hours (index 3) also treats the relationship as direct rather than inverse.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "easy",
    stem_en: "A basket holds 40 apples. If 25% of them are green, how many green apples are in the basket?",
    options_en: ["8", "10", "15", "20"], correct_index: 1,
    stem_ar: "تحتوي سلة على 40 تفاحة. إذا كان 25% منها أخضر، فكم عدد التفاحات الخضراء في السلة؟",
    options_ar: ["8", "10", "15", "20"],
    rationale_en: "25% of 40 = 0.25 x 40 = 10 (key, index 1). 8 (index 0) comes from 20% of 40. 15 (index 2) has no valid basis. 20 (index 3) is 50% of 40, doubling the required percentage.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "easy",
    stem_en: "A walking path is 60 metres long. A child has walked 30% of it. How many metres has the child walked?",
    options_en: ["12", "18", "20", "30"], correct_index: 1,
    stem_ar: "مسار للمشي طوله 60 مترًا. مشى طفل 30% منه. كم مترًا مشى الطفل؟",
    options_ar: ["12", "18", "20", "30"],
    rationale_en: "30% of 60 = 0.30 x 60 = 18 (key, index 1). 12 (index 0) is 20% of 60. 20 (index 2) is one-third of 60, confusing 30% with 33%. 30 (index 3) is half of 60, treating 30% as 50%.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "easy",
    stem_en: "There are 200 seats in a hall. If 10% of the seats are empty, how many seats are empty?",
    options_en: ["10", "20", "30", "100"], correct_index: 1,
    stem_ar: "يوجد 200 مقعد في قاعة. إذا كان 10% من المقاعد فارغة، فكم عدد المقاعد الفارغة؟",
    options_ar: ["10", "20", "30", "100"],
    rationale_en: "10% of 200 = 0.10 x 200 = 20 (key, index 1). 10 (index 0) takes 10% of 100 instead of 200. 30 (index 2) has no valid basis. 100 (index 3) is 50% of 200, ignoring the actual percentage.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "medium",
    stem_en: "A plant was 50 cm tall last month. This month it is 20% taller. How tall is the plant now?",
    options_en: ["55 cm", "60 cm", "70 cm", "100 cm"], correct_index: 1,
    stem_ar: "كان طول نبتة 50 سم في الشهر الماضي. هذا الشهر أصبحت أطول بنسبة 20%. كم يبلغ طول النبتة الآن؟",
    options_ar: ["55 سم", "60 سم", "70 سم", "100 سم"],
    rationale_en: "A 20% increase means adding 20% of 50 (which is 10) to 50, giving 60 cm (key, index 1). 55 cm (index 0) adds only 10% (5 cm). 70 cm (index 2) adds 40% instead of 20%. 100 cm (index 3) doubles the height, treating the increase as 100%.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "medium",
    stem_en: "A jug held 80 mL of water. After some evaporated, only 60 mL remains. By what percentage did the amount of water decrease?",
    options_en: ["20%", "25%", "30%", "33%"], correct_index: 1,
    stem_ar: "احتوى إبريق على 80 مل من الماء. بعد تبخر بعضه، بقي 60 مل فقط. بأي نسبة مئوية نقصت كمية الماء؟",
    options_ar: ["20%", "25%", "30%", "33%"],
    rationale_en: "The decrease is 80 - 60 = 20 mL, measured against the original: 20/80 = 0.25 = 25% (key, index 1). 20% (index 0) reads the raw drop of 20 as a percentage. 30% (index 2) has no basis. 33% (index 3) divides 20 by the new amount 60 instead of the original 80.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "medium",
    stem_en: "After a 10% discount, a toy costs 45 coins. What was the price of the toy before the discount?",
    options_en: ["49.5 coins", "50 coins", "55 coins", "55.5 coins"], correct_index: 1,
    stem_ar: "بعد خصم 10%، أصبح سعر لعبة 45 قطعة نقدية. كم كان سعر اللعبة قبل الخصم؟",
    options_ar: ["49.5 قطعة نقدية", "50 قطعة نقدية", "55 قطعة نقدية", "55.5 قطعة نقدية"],
    rationale_en: "After a 10% discount the price is 90% of the original, so original = 45 / 0.90 = 50 coins (key, index 1). Check: 10% of 50 is 5, and 50 - 5 = 45. 49.5 (index 0) adds 10% of 45 (4.5) to 45, applying the percentage to the discounted price. 55 (index 2) adds a flat 10 coins. 55.5 (index 3) adds a mistaken larger amount.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "medium",
    stem_en: "In a box of 25 pencils, 5 are broken. What percentage of the pencils are broken?",
    options_en: ["15%", "20%", "25%", "40%"], correct_index: 1,
    stem_ar: "في علبة تحتوي على 25 قلم رصاص، يوجد 5 أقلام مكسورة. ما النسبة المئوية للأقلام المكسورة؟",
    options_ar: ["15%", "20%", "25%", "40%"],
    rationale_en: "5 out of 25 = 5/25 = 0.20 = 20% (key, index 1). 15% (index 0) has no valid basis. 25% (index 2) comes from 5/20, using the unbroken count as the base. 40% (index 3) comes from doubling the correct answer.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "hard",
    stem_en: "A rope was 120 cm long. It was first cut by 25%, then 20% of the remaining length was cut off. What is the final length of the rope?",
    options_en: ["66 cm", "72 cm", "78 cm", "90 cm"], correct_index: 1,
    stem_ar: "كان طول حبل 120 سم. تم قطع 25% منه أولاً، ثم قُطع 20% من الطول المتبقي. ما الطول النهائي للحبل؟",
    options_ar: ["66 سم", "72 سم", "78 سم", "90 سم"],
    rationale_en: "After cutting 25% of 120, the remaining length is 0.75 x 120 = 90 cm. Then 20% of 90 is cut, leaving 0.80 x 90 = 72 cm (key, index 1). 66 cm (index 0) subtracts a combined 45% of 120. 78 cm (index 2) subtracts 20% of the original 120 (24 cm) from 90 rather than 20% of 90. 90 cm (index 3) stops after the first cut.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "hard",
    stem_en: "Two boxes each start with the same number of marbles. Box A gains 10% more marbles, and Box B loses 10% of its marbles. If Box A now has 66 marbles, how many marbles does Box B have now?",
    options_en: ["48", "54", "56", "60"], correct_index: 1,
    stem_ar: "يبدأ صندوقان بنفس عدد الكرات الزجاجية. يكسب الصندوق (أ) 10% كرات إضافية، ويفقد الصندوق (ب) 10% من كراته. إذا أصبح لدى الصندوق (أ) الآن 66 كرة، فكم عدد الكرات في الصندوق (ب) الآن؟",
    options_ar: ["48", "54", "56", "60"],
    rationale_en: "Box A having 66 after a 10% gain means the start was 66 / 1.10 = 60. Box B loses 10% of 60, so it has 0.90 x 60 = 54 (key, index 1). 48 (index 0) subtracts 20% instead of 10%. 56 (index 2) subtracts a flat 10 from 66 or 10% of 66. 60 (index 3) forgets to apply Box B's loss.",
  },
  {
    subtest: "numerical", facet: "num_percent", difficulty: "hard",
    stem_en: "A number is increased by 50%, and then the result is decreased by 40%. Compared with the original number, the final value is:",
    options_en: ["10% larger", "10% smaller", "20% larger", "the same"], correct_index: 1,
    stem_ar: "يُزاد عدد بنسبة 50%، ثم يُنقص الناتج بنسبة 40%. بالمقارنة مع العدد الأصلي، تكون القيمة النهائية:",
    options_ar: ["أكبر بنسبة 10%", "أصغر بنسبة 10%", "أكبر بنسبة 20%", "نفس القيمة"],
    rationale_en: "Take the original as 100. A 50% increase gives 150. A 40% decrease of 150 is 150 x 0.60 = 90. Since 90 is less than 100, the final value is 10% smaller (key, index 1). '10% larger' (index 0) nets the percentages as +50-40=+10 applied to the original. '20% larger' (index 2) has no valid basis. 'the same' (index 3) wrongly assumes +50% and -40% cancel.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "easy",
    stem_en: "A weather log lists the high temperature for four days: Monday 22°C, Tuesday 19°C, Wednesday 25°C, Thursday 21°C. What was the highest temperature recorded?",
    options_en: ["19°C", "21°C", "22°C", "25°C"], correct_index: 3,
    stem_ar: "يسجل سجل الطقس درجة الحرارة العليا لأربعة أيام: الاثنين 22 درجة مئوية، الثلاثاء 19 درجة مئوية، الأربعاء 25 درجة مئوية، الخميس 21 درجة مئوية. ما هي أعلى درجة حرارة سُجّلت؟",
    options_ar: ["19 درجة مئوية", "21 درجة مئوية", "22 درجة مئوية", "25 درجة مئوية"],
    rationale_en: "Scanning the four values, 25°C (Wednesday) is the largest (key, index 3). 19°C is the lowest, 22°C is Monday's value, and 21°C is Thursday's value; none is the maximum.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "easy",
    stem_en: "A table shows books read per month: January 3, February 5, March 4. How many books were read in total across the three months?",
    options_en: ["11", "12", "13", "15"], correct_index: 1,
    stem_ar: "يوضّح جدول عدد الكتب المقروءة في كل شهر: يناير 3، فبراير 5، مارس 4. كم عدد الكتب المقروءة إجمالاً خلال الأشهر الثلاثة؟",
    options_ar: ["11", "12", "13", "15"],
    rationale_en: "Adding the three values: 3 + 5 + 4 = 12 (key, index 1). 11 (index 0) omits a book. 13 (index 2) adds one extra. 15 (index 3) mistakenly multiplies 5 x 3 or over-sums.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "easy",
    stem_en: "A chart of daily rainfall reads: Day 1 = 6 mm, Day 2 = 6 mm, Day 3 = 9 mm, Day 4 = 3 mm. On how many days was the rainfall exactly 6 mm?",
    options_en: ["1", "2", "3", "4"], correct_index: 1,
    stem_ar: "يعرض مخطط لكمية الأمطار اليومية: اليوم 1 = 6 مم، اليوم 2 = 6 مم، اليوم 3 = 9 مم، اليوم 4 = 3 مم. في كم يوم كانت كمية الأمطار 6 مم بالضبط؟",
    options_ar: ["1", "2", "3", "4"],
    rationale_en: "Days 1 and 2 both read 6 mm, so exactly 2 days match (key, index 1). 1 (index 0) counts only one matching day. 3 (index 2) and 4 (index 3) over-count by including Day 3 (9 mm) or Day 4 (3 mm), which do not equal 6 mm.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "medium",
    stem_en: "A table lists the distance walked each day: Monday 4 km, Tuesday 7 km, Wednesday 5 km, Thursday 8 km. How much farther was walked on Thursday than on Monday?",
    options_en: ["3 km", "4 km", "8 km", "12 km"], correct_index: 1,
    stem_ar: "يسرد جدول المسافة المقطوعة مشياً كل يوم: الاثنين 4 كم، الثلاثاء 7 كم، الأربعاء 5 كم، الخميس 8 كم. كم كانت المسافة المقطوعة يوم الخميس أكثر منها يوم الاثنين؟",
    options_ar: ["3 كم", "4 كم", "8 كم", "12 كم"],
    rationale_en: "The difference is Thursday minus Monday: 8 - 4 = 4 km (key, index 1). 3 km (index 0) subtracts the wrong pair. 8 km (index 2) is Thursday's raw value. 12 km (index 3) adds the two days instead of subtracting.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "medium",
    stem_en: "A table shows cups of water drunk per day: Sunday 6, Monday 8, Tuesday 7. What is the average number of cups per day over these three days?",
    options_en: ["6", "7", "8", "21"], correct_index: 1,
    stem_ar: "يوضّح جدول عدد أكواب الماء المشروبة يومياً: الأحد 6، الاثنين 8، الثلاثاء 7. ما هو متوسط عدد الأكواب يومياً خلال هذه الأيام الثلاثة؟",
    options_ar: ["6", "7", "8", "21"],
    rationale_en: "The average is the sum divided by the count: (6 + 8 + 7) / 3 = 21 / 3 = 7 (key, index 1). 6 (index 0) and 8 (index 2) are individual daily values mistaken for the average. 21 (index 3) is the total, not divided.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "medium",
    stem_en: "A parking log records cars entering each hour: 9 a.m. = 12, 10 a.m. = 15, 11 a.m. = 12, 12 p.m. = 9. Which two hours had the same number of cars entering?",
    options_en: ["9 a.m. and 10 a.m.", "9 a.m. and 11 a.m.", "10 a.m. and 12 p.m.", "11 a.m. and 12 p.m."], correct_index: 1,
    stem_ar: "يسجّل سجل مواقف السيارات عدد السيارات الداخلة كل ساعة: 9 صباحاً = 12، 10 صباحاً = 15، 11 صباحاً = 12، 12 ظهراً = 9. أي ساعتين كان فيهما نفس عدد السيارات الداخلة؟",
    options_ar: ["9 صباحاً و10 صباحاً", "9 صباحاً و11 صباحاً", "10 صباحاً و12 ظهراً", "11 صباحاً و12 ظهراً"],
    rationale_en: "The 9 a.m. and 11 a.m. entries both read 12 cars (key, index 1). The 9/10 pair is 12 vs 15, the 10/12 pair is 15 vs 9, and the 11/12 pair is 12 vs 9 - none of these are equal.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "medium",
    stem_en: "A table of items collected reads: red 8, blue 5, green 8, yellow 4. Red and green together make up what fraction of all items collected?",
    options_en: ["8/25", "16/25", "13/25", "1/2"], correct_index: 1,
    stem_ar: "يقرأ جدول العناصر المجمّعة: أحمر 8، أزرق 5، أخضر 8، أصفر 4. ما هي النسبة التي يشكّلها الأحمر والأخضر معاً من إجمالي العناصر المجمّعة؟",
    options_ar: ["8/25", "16/25", "13/25", "1/2"],
    rationale_en: "Total items = 8 + 5 + 8 + 4 = 25; red plus green = 8 + 8 = 16, giving 16/25 (key, index 1). 8/25 (index 0) counts only one colour. 13/25 (index 2) mistakenly adds red + blue (8 + 5). 1/2 (index 3) wrongly assumes half.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "hard",
    stem_en: "A table shows visitors to a park over four days: Thursday 40, Friday 60, Saturday 90, Sunday 50. By what percentage did visitor numbers increase from Thursday to Saturday?",
    options_en: ["50%", "80%", "90%", "125%"], correct_index: 3,
    stem_ar: "يوضّح جدول عدد زوار حديقة على مدى أربعة أيام: الخميس 40، الجمعة 60، السبت 90، الأحد 50. بأي نسبة مئوية زاد عدد الزوار من الخميس إلى السبت؟",
    options_ar: ["50%", "80%", "90%", "125%"],
    rationale_en: "The increase is Saturday minus Thursday = 90 - 40 = 50, taken as a percentage of the Thursday base: 50 / 40 = 1.25 = 125% (key, index 3). 50% (index 0) reads the raw increase of 50 as a percent. 80% (index 1) divides by the wrong base. 90% (index 2) is Saturday's raw count.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "hard",
    stem_en: "A chart lists the length of four trails: Trail A 3.5 km, Trail B 4.2 km, Trail C 2.8 km, Trail D 5.5 km. A hiker walks Trails A, C, and D. What is the total distance walked?",
    options_en: ["10.5 km", "11.8 km", "12.0 km", "16.0 km"], correct_index: 1,
    stem_ar: "يسرد مخطط طول أربعة مسارات: المسار أ 3.5 كم، المسار ب 4.2 كم، المسار ج 2.8 كم، المسار د 5.5 كم. يمشي متنزّه المسارات أ وج ود. ما هي المسافة الإجمالية المقطوعة؟",
    options_ar: ["10.5 كم", "11.8 كم", "12.0 كم", "16.0 كم"],
    rationale_en: "Adding only the walked trails A, C, and D: 3.5 + 2.8 + 5.5 = 11.8 km (key, index 1). 10.5 km (index 0) omits one trail. 12.0 km (index 2) reflects a rounding/addition slip. 16.0 km (index 3) sums all four trails including B.",
  },
  {
    subtest: "numerical", facet: "num_data", difficulty: "hard",
    stem_en: "A table shows a runner's times for four laps: Lap 1 = 65 s, Lap 2 = 70 s, Lap 3 = 60 s, Lap 4 = 69 s. How much slower was the slowest lap than the average lap time?",
    options_en: ["2 s", "4 s", "6 s", "10 s"], correct_index: 1,
    stem_ar: "يوضّح جدول أزمنة عدّاء لأربع لفّات: اللفة 1 = 65 ثانية، اللفة 2 = 70 ثانية، اللفة 3 = 60 ثانية، اللفة 4 = 69 ثانية. بكم كانت أبطأ لفة أبطأ من متوسط زمن اللفة؟",
    options_ar: ["2 ثانية", "4 ثانية", "6 ثانية", "10 ثانية"],
    rationale_en: "The average lap time is (65 + 70 + 60 + 69) / 4 = 264 / 4 = 66 s; the slowest lap is 70 s, so 70 - 66 = 4 s (key, index 1). 2 s (index 0) uses a miscomputed average. 6 s (index 2) mixes up the reference point. 10 s (index 3) is the raw spread between fastest (60) and slowest (70).",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "easy",
    stem_en: "Puppy is to dog as kitten is to:",
    options_en: ["Cat", "Bird", "Mouse", "Fish"], correct_index: 0,
    stem_ar: "الجرو إلى الكلب كما الهريرة إلى:",
    options_ar: ["القط", "الطائر", "الفأر", "السمكة"],
    rationale_en: "Young-to-adult of the same animal: a puppy is a young dog, so a kitten is a young cat. The other options are unrelated animals.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "easy",
    stem_en: "Hot is to cold as tall is to:",
    options_en: ["Wide", "Short", "Heavy", "Fast"], correct_index: 1,
    stem_ar: "الحار إلى البارد كما الطويل إلى:",
    options_ar: ["العريض", "القصير", "الثقيل", "السريع"],
    rationale_en: "Opposites: hot/cold, so tall/short. Wide, heavy, and fast are different dimensions, not the opposite of tall.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "easy",
    stem_en: "Finger is to hand as toe is to:",
    options_en: ["Arm", "Head", "Foot", "Knee"], correct_index: 2,
    stem_ar: "الإصبع إلى اليد كما إصبع القدم إلى:",
    options_ar: ["الذراع", "الرأس", "القدم", "الركبة"],
    rationale_en: "Part-to-whole: a finger is part of a hand, so a toe is part of a foot. The other body parts do not contain the toe.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "medium",
    stem_en: "Author is to book as composer is to:",
    options_en: ["Painting", "Symphony", "Orchestra", "Stage"], correct_index: 1,
    stem_ar: "المؤلف إلى الكتاب كما الملحّن إلى:",
    options_ar: ["اللوحة", "السيمفونية", "الأوركسترا", "المسرح"],
    rationale_en: "Creator-to-creation: an author creates a book, a composer creates a symphony. A painting is a painter's work; an orchestra performs and a stage hosts, neither is the created work.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "medium",
    stem_en: "Thermometer is to temperature as clock is to:",
    options_en: ["Weight", "Speed", "Time", "Distance"], correct_index: 2,
    stem_ar: "الميزان الحراري إلى الحرارة كما الساعة إلى:",
    options_ar: ["الوزن", "السرعة", "الوقت", "المسافة"],
    rationale_en: "Instrument-to-what-it-measures: a thermometer measures temperature, a clock measures time. Weight, speed, and distance are measured by other instruments.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "medium",
    stem_en: "Drought is to famine as spark is to:",
    options_en: ["Fire", "Smoke", "Match", "Wood"], correct_index: 0,
    stem_ar: "الجفاف إلى المجاعة كما الشرارة إلى:",
    options_ar: ["الحريق", "الدخان", "عود الثقاب", "الخشب"],
    rationale_en: "Cause-to-effect: a drought causes a famine, a spark causes a fire. Smoke is a result of fire, a match is a source of a spark, and wood is fuel, not the effect.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "medium",
    stem_en: "Whisper is to shout as trickle is to:",
    options_en: ["Drip", "Puddle", "Flood", "Splash"], correct_index: 2,
    stem_ar: "الهمس إلى الصراخ كما التقاطر إلى:",
    options_ar: ["التنقيط", "البِركة", "الفيضان", "الرذاذ"],
    rationale_en: "Small-to-large in intensity: a whisper is faint and a shout intense, so the intense counterpart of a small trickle is a flood. Drip is equally small, puddle is static, and splash is a brief scatter.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "hard",
    stem_en: "Sculptor is to chisel as writer is to:",
    options_en: ["Book", "Pen", "Reader", "Desk"], correct_index: 1,
    stem_ar: "النحّات إلى الإزميل كما الكاتب إلى:",
    options_ar: ["الكتاب", "القلم", "القارئ", "المكتب"],
    rationale_en: "Worker-to-their-tool: a sculptor works with a chisel, a writer works with a pen. A book is the product, a reader is the audience, and a desk is furniture, not the instrument.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "hard",
    stem_en: "Petal is to flower as scale is to:",
    options_en: ["Bird", "Fish", "Snake", "Tree"], correct_index: 1,
    stem_ar: "البتلة إلى الزهرة كما الحرشفة إلى:",
    options_ar: ["الطائر", "السمكة", "الأفعى", "الشجرة"],
    rationale_en: "Many small overlapping parts covering the whole: petals form a flower, scales cover a fish. A bird is covered by feathers and a tree by bark; a fish's surface, uniformly built of overlapping scales, is the closest fit and stronger than snake.",
  },
  {
    subtest: "verbal", facet: "verb_analogy", difficulty: "hard",
    stem_en: "Reckless is to caution as generous is to:",
    options_en: ["Kindness", "Stinginess", "Wealth", "Charity"], correct_index: 1,
    stem_ar: "المتهوّر إلى الحذر كما الكريم إلى:",
    options_ar: ["اللطف", "البُخل", "الثروة", "الصدقة"],
    rationale_en: "A trait paired with the quality it lacks: a reckless person lacks caution, a generous person lacks stinginess. Kindness and charity are qualities a generous person has; wealth is unrelated.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "easy",
    stem_en: "The library closes at eight o'clock on weekdays, but on Saturdays it closes two hours earlier. It stays shut all day Sunday. According to the passage, when does the library close on Saturday?",
    options_en: ["At six o'clock", "At eight o'clock", "At ten o'clock", "It is closed all day Saturday"], correct_index: 0,
    stem_ar: "تُغلق المكتبة أبوابها في الساعة الثامنة في أيام الأسبوع، لكنها تُغلق قبل ذلك بساعتين يوم السبت. وتبقى مغلقة طوال يوم الأحد. وفقًا للنص، متى تُغلق المكتبة يوم السبت؟",
    options_ar: ["في الساعة السادسة", "في الساعة الثامنة", "في الساعة العاشرة", "تكون مغلقة طوال يوم السبت"],
    rationale_en: "Weekday closing is eight; Saturday is two hours earlier, so six o'clock. Eight is the weekday time, ten adds instead of subtracts, and 'closed all day' confuses Saturday with Sunday.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "easy",
    stem_en: "Maryam packed her bag the night before the trip. She remembered her umbrella, her water bottle, and her hat, but she forgot her sunglasses on the kitchen table. Which item did Maryam leave behind?",
    options_en: ["Her water bottle", "Her sunglasses", "Her hat", "Her umbrella"], correct_index: 1,
    stem_ar: "حزمت مريم حقيبتها في الليلة السابقة للرحلة. تذكّرت مظلتها وقارورة الماء والقبعة، لكنها نسيت نظارتها الشمسية على طاولة المطبخ. أي غرض تركته مريم خلفها؟",
    options_ar: ["قارورة الماء", "نظارتها الشمسية", "قبعتها", "مظلتها"],
    rationale_en: "The passage says she forgot her sunglasses on the kitchen table. The water bottle, hat, and umbrella are all listed among the items she remembered.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "easy",
    stem_en: "The garden has three apple trees and one pear tree. The pear tree is the tallest of them all. Only the pear tree has fruit this season. Which statement is true according to the passage?",
    options_en: ["The apple trees are taller than the pear tree", "There are more pear trees than apple trees", "The pear tree has fruit this season", "None of the trees has fruit this season"], correct_index: 2,
    stem_ar: "تحتوي الحديقة على ثلاث أشجار تفاح وشجرة كمثرى واحدة. شجرة الكمثرى هي الأطول بينها جميعًا. وحدها شجرة الكمثرى تحمل ثمارًا هذا الموسم. أي عبارة صحيحة وفقًا للنص؟",
    options_ar: ["أشجار التفاح أطول من شجرة الكمثرى", "عدد أشجار الكمثرى أكثر من أشجار التفاح", "شجرة الكمثرى تحمل ثمارًا هذا الموسم", "لا تحمل أي من الأشجار ثمارًا هذا الموسم"],
    rationale_en: "The passage states only the pear tree has fruit. The pear tree is the tallest, there is one pear versus three apples, and the pear tree does bear fruit, ruling out the others.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "medium",
    stem_en: "The museum guide explained that the blue vase came from the eastern workshop, while the green vase and the tall jug both came from the northern workshop. The small bowl was the only piece made locally. According to the passage, which piece was made locally?",
    options_en: ["The blue vase", "The green vase", "The tall jug", "The small bowl"], correct_index: 3,
    stem_ar: "أوضح مرشد المتحف أن المزهرية الزرقاء جاءت من الورشة الشرقية، بينما جاءت المزهرية الخضراء والإبريق الطويل كلاهما من الورشة الشمالية. وكان الوعاء الصغير القطعة الوحيدة المصنوعة محليًا. وفقًا للنص، أي قطعة صُنعت محليًا؟",
    options_ar: ["المزهرية الزرقاء", "المزهرية الخضراء", "الإبريق الطويل", "الوعاء الصغير"],
    rationale_en: "The passage states the small bowl was the only piece made locally. The blue vase came from the eastern workshop, and the green vase and tall jug from the northern workshop.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "medium",
    stem_en: "The passage describes a festival that runs for three days. On the first day there is a parade, on the second day a music concert, and on the third day a closing feast. Rain is expected only on the second day. According to the passage, what event may be affected by rain?",
    options_en: ["The parade", "The music concert", "The closing feast", "The opening ceremony"], correct_index: 1,
    stem_ar: "يصف النص مهرجانًا يستمر ثلاثة أيام. في اليوم الأول هناك موكب، وفي اليوم الثاني حفل موسيقي، وفي اليوم الثالث وليمة ختامية. ويُتوقع هطول المطر في اليوم الثاني فقط. وفقًا للنص، أي فعالية قد تتأثر بالمطر؟",
    options_ar: ["الموكب", "الحفل الموسيقي", "الوليمة الختامية", "حفل الافتتاح"],
    rationale_en: "Rain is expected only on the second day, which is the music concert. The parade is the first day and the feast the third; an opening ceremony is not mentioned.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "medium",
    stem_en: "Sami usually walks to the market, which takes twenty minutes. Today the direct path was blocked, so he took a longer route that added ten minutes to his usual time. He left home at nine o'clock. When did Sami reach the market today?",
    options_en: ["At 9:10", "At 9:20", "At 9:30", "At 9:40"], correct_index: 2,
    stem_ar: "عادةً ما يمشي سامي إلى السوق، وتستغرق الرحلة عشرين دقيقة. اليوم كان الطريق المباشر مغلقًا، فسلك طريقًا أطول أضاف عشر دقائق إلى وقته المعتاد. غادر المنزل في الساعة التاسعة. متى وصل سامي إلى السوق اليوم؟",
    options_ar: ["في الساعة 9:10", "في الساعة 9:20", "في الساعة 9:30", "في الساعة 9:40"],
    rationale_en: "Usual 20 minutes plus 10 added equals 30, so leaving at 9:00 he arrives at 9:30. The distractors use only the extra time, only the usual time, or double the delay.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "medium",
    stem_en: "The recipe makes twelve small cakes and uses two cups of flour. Rania wants to make exactly twenty-four cakes for a gathering, keeping the same recipe proportions. According to the passage, how many cups of flour will she need?",
    options_en: ["Two cups", "Three cups", "Four cups", "Six cups"], correct_index: 2,
    stem_ar: "الوصفة تُنتج اثنتي عشرة كعكة صغيرة وتستخدم كوبين من الطحين. تريد رانيا أن تصنع أربعًا وعشرين كعكة بالضبط لتجمّع، مع الحفاظ على النسب نفسها في الوصفة. وفقًا للنص، كم كوبًا من الطحين ستحتاج؟",
    options_ar: ["كوبان", "ثلاثة أكواب", "أربعة أكواب", "ستة أكواب"],
    rationale_en: "Twenty-four cakes is double twelve, so the two cups of flour double to four. The distractors ignore the doubling, add one, or triple the amount.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "hard",
    stem_en: "The article notes that the old lighthouse, once the tallest structure on the coast, was surpassed in height by a new hotel built last year. The lighthouse remains, however, the oldest building still standing in the town. According to the passage, which statement is accurate?",
    options_en: ["The lighthouse is now the tallest structure on the coast", "The hotel is older than the lighthouse", "The lighthouse is the oldest building still standing in the town", "The hotel is the oldest building in the town"], correct_index: 2,
    stem_ar: "يشير المقال إلى أن المنارة القديمة، التي كانت يومًا أطول بناء على الساحل، تجاوزها في الارتفاع فندق جديد شُيِّد العام الماضي. ومع ذلك تبقى المنارة أقدم مبنى ما زال قائمًا في البلدة. وفقًا للنص، أي عبارة دقيقة؟",
    options_ar: ["المنارة الآن أطول بناء على الساحل", "الفندق أقدم من المنارة", "المنارة أقدم مبنى ما زال قائمًا في البلدة", "الفندق أقدم مبنى في البلدة"],
    rationale_en: "The passage states the lighthouse remains the oldest building still standing. It is no longer the tallest (the hotel surpassed it), and the hotel is new, not old.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "hard",
    stem_en: "A travel review says the coastal trail offers wide sea views but little shade, while the forest trail is shaded throughout yet reveals the sea only at its very end. A visitor who wants shade for most of the walk but still hopes to glimpse the sea would, according to the review, be best suited by which trail?",
    options_en: ["The coastal trail", "The forest trail", "Neither trail offers any sea view", "Both trails are fully shaded"], correct_index: 1,
    stem_ar: "يقول تقييم سياحي إن المسار الساحلي يوفر إطلالات بحرية واسعة لكن ظلًا قليلًا، بينما المسار الحرجي مظلَّل طوال الطريق لكنه يكشف البحر عند نهايته فقط. الزائر الذي يريد ظلًا في معظم المسير لكنه يأمل مع ذلك في لمح البحر، وفقًا للتقييم، أي مسار يناسبه أكثر؟",
    options_ar: ["المسار الساحلي", "المسار الحرجي", "لا يوفر أي من المسارين إطلالة بحرية", "كلا المسارين مظلَّل بالكامل"],
    rationale_en: "The forest trail is shaded throughout and still reveals the sea at its end, matching both wishes. The coastal trail lacks shade; the two remaining options contradict the passage, which gives both trails a sea view and only one full shade.",
  },
  {
    subtest: "verbal", facet: "verb_comprehension", difficulty: "hard",
    stem_en: "The report states that the northern branch handled more visitors than the central branch, and that the central branch handled more than the southern branch. It gives no figures for any other branch. Based only on the passage, which statement can be made with certainty about visitor numbers?",
    options_en: ["The southern branch handled the most visitors", "The northern branch handled more visitors than the southern branch", "The central branch handled the fewest visitors", "The northern and southern branches handled equal numbers"], correct_index: 1,
    stem_ar: "يذكر التقرير أن الفرع الشمالي استقبل زوارًا أكثر من الفرع المركزي، وأن الفرع المركزي استقبل أكثر من الفرع الجنوبي. ولا يعطي أرقامًا لأي فرع آخر. بناءً على النص وحده، أي عبارة يمكن الجزم بها بشأن أعداد الزوار؟",
    options_ar: ["استقبل الفرع الجنوبي أكبر عدد من الزوار", "استقبل الفرع الشمالي زوارًا أكثر من الفرع الجنوبي", "استقبل الفرع المركزي أقل عدد من الزوار", "استقبل الفرعان الشمالي والجنوبي أعدادًا متساوية"],
    rationale_en: "The passage places northern above central and central above southern, so northern above southern is certain. Southern is not the most, central is the middle not the fewest, and no equality is stated.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "easy",
    stem_en: "The path to the lake was quite narrow, so we walked in single file. In this sentence, \"narrow\" is closest in meaning to:",
    options_en: ["wide", "thin", "steep", "long"], correct_index: 1,
    stem_ar: "كان الطريق إلى البحيرة ضيقًا جدًا، لذلك مشينا في صف واحد. في هذه الجملة، كلمة \"ضيق\" أقرب في المعنى إلى:",
    options_ar: ["عريض", "نحيل", "شديد الانحدار", "طويل"],
    rationale_en: "A narrow path is thin from side to side, so 'thin' is closest. 'Wide' is the opposite, 'steep' describes slope, and 'long' describes distance.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "easy",
    stem_en: "She was glad to see her old friend after so many years apart. In this sentence, \"glad\" is closest in meaning to:",
    options_en: ["tired", "pleased", "surprised", "nervous"], correct_index: 1,
    stem_ar: "كانت مسرورة برؤية صديقتها القديمة بعد سنوات طويلة من الفراق. في هذه الجملة، كلمة \"مسرورة\" أقرب في المعنى إلى:",
    options_ar: ["متعبة", "سعيدة", "متفاجئة", "متوترة"],
    rationale_en: "'Glad' means happy or pleased. 'Tired' and 'nervous' are unrelated; 'surprised' is a reaction to the unexpected, not the feeling of gladness.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "easy",
    stem_en: "He tried to mend the broken chair before anyone noticed. In this sentence, \"mend\" is closest in meaning to:",
    options_en: ["repair", "hide", "sell", "clean"], correct_index: 0,
    stem_ar: "حاول أن يصلح الكرسي المكسور قبل أن يلاحظ أحد. في هذه الجملة، كلمة \"يصلح\" أقرب في المعنى إلى:",
    options_ar: ["يُرمِّم", "يُخفي", "يبيع", "ينظّف"],
    rationale_en: "To 'mend' a broken object means to repair it. 'Hide' is a separate action, and 'sell' and 'clean' are unrelated to fixing something broken.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "medium",
    stem_en: "The instructions were vague, so nobody was sure which room to enter. In this sentence, \"vague\" is closest in meaning to:",
    options_en: ["detailed", "unclear", "strict", "loud"], correct_index: 1,
    stem_ar: "كانت التعليمات غامضة، لذلك لم يكن أحد متأكدًا من الغرفة التي يدخلها. في هذه الجملة، كلمة \"غامضة\" أقرب في المعنى إلى:",
    options_ar: ["مفصّلة", "غير واضحة", "صارمة", "عالية الصوت"],
    rationale_en: "'Vague' means lacking clarity, so 'unclear' fits, cued by nobody being sure. 'Detailed' is the opposite, 'strict' concerns enforcement, and 'loud' concerns volume.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "medium",
    stem_en: "The manager was reluctant to change the schedule everyone had already learned. In this sentence, \"reluctant\" is closest in meaning to:",
    options_en: ["unwilling", "unable", "quick", "delighted"], correct_index: 0,
    stem_ar: "كان المسؤول مترددًا في تغيير الجدول الذي تعلمه الجميع بالفعل. في هذه الجملة، كلمة \"متردد\" أقرب في المعنى إلى:",
    options_ar: ["غير راغب", "غير قادر", "سريع", "مسرور"],
    rationale_en: "'Reluctant' means hesitant or unwilling. 'Unable' means lacking ability, which differs from choosing not to; 'quick' and 'delighted' carry no hesitation.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "medium",
    stem_en: "The children were curious about the strange sound coming from the garden. In this sentence, \"curious\" is closest in meaning to:",
    options_en: ["frightened", "bored", "inquisitive", "polite"], correct_index: 2,
    stem_ar: "كان الأطفال فضوليين بشأن الصوت الغريب القادم من الحديقة. في هذه الجملة، كلمة \"فضوليين\" أقرب في المعنى إلى:",
    options_ar: ["خائفين", "يشعرون بالملل", "مُتَطَلِّعين للمعرفة", "مؤدّبين"],
    rationale_en: "'Curious' means eager to know, so 'inquisitive' matches. 'Frightened' is fear not interest, 'bored' is the opposite, and 'polite' is unrelated.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "medium",
    stem_en: "The old bridge looked fragile, so the hikers crossed it one at a time. In this sentence, \"fragile\" is closest in meaning to:",
    options_en: ["heavy", "delicate", "crowded", "modern"], correct_index: 1,
    stem_ar: "بدا الجسر القديم هشًا، لذلك عبره المتنزهون واحدًا تلو الآخر. في هذه الجملة، كلمة \"هش\" أقرب في المعنى إلى:",
    options_ar: ["ثقيل", "قابل للكسر", "مزدحم", "حديث"],
    rationale_en: "'Fragile' means easily broken, so 'delicate' fits, cued by crossing one at a time. 'Heavy' is weight, 'crowded' is people, and 'modern' contradicts 'old'.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "hard",
    stem_en: "Her explanation was concise, covering everything important in just two sentences. In this sentence, \"concise\" is closest in meaning to:",
    options_en: ["confusing", "brief", "loud", "honest"], correct_index: 1,
    stem_ar: "كان شرحها موجزًا، إذ غطّى كل ما هو مهم في جملتين فقط. في هذه الجملة، كلمة \"موجز\" أقرب في المعنى إلى:",
    options_ar: ["مُربِك", "مختصر", "عالي الصوت", "صادق"],
    rationale_en: "'Concise' means expressing much in few words, so 'brief' fits, cued by 'just two sentences'. A concise explanation is clear not confusing; 'loud' and 'honest' concern other qualities.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "hard",
    stem_en: "The volunteers were diligent, checking every box twice before sealing it. In this sentence, \"diligent\" is closest in meaning to:",
    options_en: ["careless", "cheerful", "hardworking", "impatient"], correct_index: 2,
    stem_ar: "كان المتطوعون مجتهدين، إذ يفحصون كل صندوق مرتين قبل إغلاقه. في هذه الجملة، كلمة \"مجتهدين\" أقرب في المعنى إلى:",
    options_ar: ["مهملين", "مبتهجين", "مجدّين في العمل", "نافدي الصبر"],
    rationale_en: "'Diligent' means careful, persistent effort, so 'hardworking' fits, cued by checking every box twice. 'Careless' is the opposite, 'cheerful' is mood, and 'impatient' is contradicted by the thorough checking.",
  },
  {
    subtest: "verbal", facet: "verb_vocab", difficulty: "hard",
    stem_en: "The witness gave a candid account of what she saw, holding nothing back. In this sentence, \"candid\" is closest in meaning to:",
    options_en: ["frank", "brief", "quiet", "doubtful"], correct_index: 0,
    stem_ar: "قدّمت الشاهدة روايةً صريحةً لما رأته، دون أن تُخفي شيئًا. في هذه الجملة، كلمة \"صريحة\" أقرب في المعنى إلى:",
    options_ar: ["مكاشِفة", "مختصرة", "هادئة", "متشكِّكة"],
    rationale_en: "'Candid' means open and honest, so 'frank' fits, reinforced by 'holding nothing back'. 'Brief' is length, 'quiet' is manner, and 'doubtful' conflicts with speaking openly.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "easy",
    stem_en: "Look at the sequence: 3, 6, 9, 12, ? What number comes next?",
    options_en: ["13", "14", "15", "18"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 3، 6، 9، 12، ؟ ما العدد التالي؟",
    options_ar: ["13", "14", "15", "18"],
    rationale_en: "The rule is +3 each step (3, 6, 9, 12), so the next term is 12 + 3 = 15. '13' adds only 1 and '14' adds 2, ignoring the constant step of 3. '18' skips a term by adding 6.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "easy",
    stem_en: "A child counts stairs: 5, 10, 15, 20, ? Which number should come next?",
    options_en: ["22", "24", "25", "30"], correct_index: 2,
    stem_ar: "يعدّ طفل الدرجات: 5، 10، 15، 20، ؟ ما العدد الذي يأتي تالياً؟",
    options_ar: ["22", "24", "25", "30"],
    rationale_en: "Each term increases by 5, so after 20 comes 25. '22' adds 2 and '24' adds 4, both below the fixed step of 5. '30' adds 10, doubling the increment and skipping 25.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "easy",
    stem_en: "Look at the letters: A, C, E, G, ? Which letter comes next?",
    options_en: ["H", "I", "J", "K"], correct_index: 1,
    stem_ar: "انظر إلى الحروف الإنجليزية: A، C، E، G، ؟ ما الحرف التالي؟",
    options_ar: ["H", "I", "J", "K"],
    rationale_en: "The letters skip one each time (moving two positions per step), so after G comes I. 'H' is only one step forward. 'J' is three steps and 'K' four, both overshooting the fixed gap of two.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "medium",
    stem_en: "Look at the sequence: 2, 6, 12, 20, ? What number comes next?",
    options_en: ["28", "30", "32", "26"], correct_index: 1,
    stem_ar: "انظر إلى المتتالية: 2، 6، 12، 20، ؟ ما العدد التالي؟",
    options_ar: ["28", "30", "32", "26"],
    rationale_en: "The gaps grow by a fixed amount: +4, +6, +8, so the next gap is +10, giving 20 + 10 = 30. '28' repeats the previous +8 gap. '32' adds 12. '26' adds only 6.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "medium",
    stem_en: "Look at the sequence: 1, 2, 4, 8, 16, ? What number comes next?",
    options_en: ["24", "30", "32", "20"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 1، 2، 4، 8، 16، ؟ ما العدد التالي؟",
    options_ar: ["24", "30", "32", "20"],
    rationale_en: "Each term is double the one before (×2), so after 16 comes 32. '24' treats it as constant addition. '30' is near but not exact. '20' adds only 4, ignoring the doubling rule.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "medium",
    stem_en: "Two lists are interleaved: 4, 40, 8, 35, 12, 30, 16, ? What number comes next?",
    options_en: ["20", "25", "24", "28"], correct_index: 1,
    stem_ar: "قائمتان متداخلتان: 4، 40، 8، 35، 12، 30، 16، ؟ ما العدد التالي؟",
    options_ar: ["20", "25", "24", "28"],
    rationale_en: "The odd positions rise by 4 (4, 8, 12, 16) and the even positions fall by 5 (40, 35, 30, ?), so the next even-position term is 30 - 5 = 25. '20' continues the rising list. '24' and '28' apply the wrong list's rule.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "medium",
    stem_en: "Look at the sequence: 1, 4, 9, 16, 25, ? What number comes next?",
    options_en: ["30", "35", "36", "49"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 1، 4، 9، 16، 25، ؟ ما العدد التالي؟",
    options_ar: ["30", "35", "36", "49"],
    rationale_en: "These are the squares of counting numbers (1², 2², 3², 4², 5²), so the next is 6² = 36. Gaps grow +3, +5, +7, +9, then +11, confirming 25 + 11 = 36. '30' adds 5, '35' adds 10. '49' is 7², skipping 6².",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "hard",
    stem_en: "Look at the sequence: 2, 3, 5, 8, 13, 21, ? What number comes next?",
    options_en: ["29", "31", "34", "42"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 2، 3، 5، 8، 13، 21، ؟ ما العدد التالي؟",
    options_ar: ["29", "31", "34", "42"],
    rationale_en: "Each term is the sum of the two before it (13 = 5+8, 21 = 8+13), so the next is 13 + 21 = 34. '29' uses an outdated gap. '31' adds only 10. '42' doubles 21, which is not the rule.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "hard",
    stem_en: "Look at the sequence: 1, 2, 6, 24, 120, ? What number comes next?",
    options_en: ["240", "600", "720", "840"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 1، 2، 6، 24، 120، ؟ ما العدد التالي؟",
    options_ar: ["240", "600", "720", "840"],
    rationale_en: "Each term is multiplied by a step that grows by one: ×2, ×3, ×4, ×5, so the next is 120 × 6 = 720. '240' just doubles 120. '600' multiplies by 5 again. '840' fits no consistent multiplier.",
  },
  {
    subtest: "inductive", facet: "ind_series", difficulty: "hard",
    stem_en: "Look at the sequence: 2, 5, 11, 23, 47, ? What number comes next?",
    options_en: ["70", "94", "95", "71"], correct_index: 2,
    stem_ar: "انظر إلى المتتالية: 2، 5، 11، 23، 47، ؟ ما العدد التالي؟",
    options_ar: ["70", "94", "95", "71"],
    rationale_en: "Each term is the previous doubled plus one (11 = 5×2+1, 23 = 11×2+1, 47 = 23×2+1), so the next is 47×2+1 = 95. '94' forgets the +1. '70' adds the prior gap. '71' fits no consistent rule.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "easy",
    stem_en: "Four words are shown. Three of them name animals; one does not. Which one does NOT belong with the others?",
    options_en: ["Rabbit", "Chair", "Horse", "Cat"], correct_index: 1,
    stem_ar: "تُعرض أربع كلمات. ثلاث منها تسمّي حيوانات، وواحدة لا. أيّها لا ينتمي إلى البقية؟",
    options_ar: ["أرنب", "كرسي", "حصان", "قطة"],
    rationale_en: "Rabbit, horse, and cat are all animals; chair is furniture, so it is the odd one out. The other three share the defining feature (being animals).",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "easy",
    stem_en: "Four numbers are shown. Three of them are even; one is not. Which number does NOT belong with the others?",
    options_en: ["8", "12", "7", "20"], correct_index: 2,
    stem_ar: "تُعرض أربعة أعداد. ثلاثة منها زوجية، وواحد ليس كذلك. أيّ عدد لا ينتمي إلى البقية؟",
    options_ar: ["8", "12", "7", "20"],
    rationale_en: "8, 12, and 20 are even; 7 is odd, so it is the odd one out. The other three are all divisible by 2.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "easy",
    stem_en: "Four words are shown. Three of them name colours; one does not. Which one does NOT belong with the others?",
    options_en: ["Green", "Blue", "River", "Yellow"], correct_index: 2,
    stem_ar: "تُعرض أربع كلمات. ثلاث منها تسمّي ألوانًا، وواحدة لا. أيّها لا ينتمي إلى البقية؟",
    options_ar: ["أخضر", "أزرق", "نهر", "أصفر"],
    rationale_en: "Green, blue, and yellow are colours; river is a body of water, so it is the odd one out. The other three belong to the shared category of colours.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "medium",
    stem_en: "Four number groups are shown. In three of them the two numbers differ by 3; in one they do not. Which group does NOT belong with the others?",
    options_en: ["(5, 8)", "(10, 13)", "(2, 5)", "(6, 10)"], correct_index: 3,
    stem_ar: "تُعرض أربع مجموعات من الأعداد. في ثلاث منها يختلف العددان بمقدار 3، وفي واحدة لا. أيّ مجموعة لا تنتمي إلى البقية؟",
    options_ar: ["(5، 8)", "(10، 13)", "(2، 5)", "(6، 10)"],
    rationale_en: "In (5,8), (10,13), and (2,5) the difference is exactly 3; in (6,10) the difference is 4, so it is the odd one out. The other three match the shared gap-of-3 rule.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "medium",
    stem_en: "Four shapes are described. Three of them have four sides; one does not. Which one does NOT belong with the others?",
    options_en: ["A square", "A rectangle", "A triangle", "A four-sided diamond"], correct_index: 2,
    stem_ar: "تُوصف أربعة أشكال. ثلاثة منها لها أربعة أضلاع، وواحد لا. أيّها لا ينتمي إلى البقية؟",
    options_ar: ["مربّع", "مستطيل", "مثلّث", "مُعيّن ذو أربعة أضلاع"],
    rationale_en: "A square, a rectangle, and a four-sided diamond all have four sides; a triangle has three, so it is the odd one out. The other three share the four-side property.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "medium",
    stem_en: "Four words are shown. Three of them read the same forwards and backwards; one does not. Which word does NOT belong with the others?",
    options_en: ["Level", "Noon", "Table", "Radar"], correct_index: 2,
    stem_ar: "تُعرض أربع كلمات إنجليزية. ثلاث منها تُقرأ بالطريقة نفسها من اليمين ومن اليسار، وواحدة لا. أيّ كلمة لا تنتمي إلى البقية؟",
    options_ar: ["Level", "Noon", "Table", "Radar"],
    rationale_en: "Level, noon, and radar are palindromes; table reversed is 'elbat', so it is the odd one out. The other three satisfy the shared palindrome rule.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "medium",
    stem_en: "Four number groups are shown. In three of them the numbers add up to 10; in one they do not. Which group does NOT belong with the others?",
    options_en: ["(3, 7)", "(4, 6)", "(2, 8)", "(5, 4)"], correct_index: 3,
    stem_ar: "تُعرض أربع مجموعات من الأعداد. في ثلاث منها يبلغ مجموع العددين 10، وفي واحدة لا. أيّ مجموعة لا تنتمي إلى البقية؟",
    options_ar: ["(3، 7)", "(4، 6)", "(2، 8)", "(5، 4)"],
    rationale_en: "3+7, 4+6, and 2+8 each total 10; 5+4 totals 9, so it is the odd one out. The first three meet the shared sum-of-10 rule.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "hard",
    stem_en: "Four numbers are shown. Three of them are perfect squares (a whole number multiplied by itself); one is not. Which number does NOT belong with the others?",
    options_en: ["36", "49", "50", "64"], correct_index: 2,
    stem_ar: "تُعرض أربعة أعداد. ثلاثة منها مربّعات كاملة (عدد صحيح مضروب في نفسه)، وواحد ليس كذلك. أيّ عدد لا ينتمي إلى البقية؟",
    options_ar: ["36", "49", "50", "64"],
    rationale_en: "36 = 6×6, 49 = 7×7, and 64 = 8×8 are perfect squares; 50 is not (it sits between 7²=49 and 8²=64), so it is the odd one out. The value 50 is a deliberately close distractor.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "hard",
    stem_en: "Four number groups are shown. In three of them the second number is double the first; in one the relationship is different. Which group does NOT belong with the others?",
    options_en: ["(3, 6)", "(7, 14)", "(9, 18)", "(6, 15)"], correct_index: 3,
    stem_ar: "تُعرض أربع مجموعات من الأعداد. في ثلاث منها العدد الثاني ضِعف الأول، وفي واحدة العلاقة مختلفة. أيّ مجموعة لا تنتمي إلى البقية؟",
    options_ar: ["(3، 6)", "(7، 14)", "(9، 18)", "(6، 15)"],
    rationale_en: "In (3,6), (7,14), and (9,18) the second number is exactly twice the first; in (6,15) it is 2.5 times the first (double would be 12), so it is the odd one out. (6,15) is a subtle distractor because 15 is still larger than double.",
  },
  {
    subtest: "inductive", facet: "ind_oddoneout", difficulty: "hard",
    stem_en: "Four numbers are shown. Three of them are multiples of 6; one is not. Which number does NOT belong with the others?",
    options_en: ["18", "24", "30", "28"], correct_index: 3,
    stem_ar: "تُعرض أربعة أعداد. ثلاثة منها من مضاعفات العدد 6، وواحد ليس كذلك. أيّ عدد لا ينتمي إلى البقية؟",
    options_ar: ["18", "24", "30", "28"],
    rationale_en: "18 = 6×3, 24 = 6×4, and 30 = 6×5 are all multiples of 6; 28 is not (6×4=24, 6×5=30, with nothing at 28), so it is the odd one out. 28 is a deliberately close even distractor sitting between two real multiples of 6.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "easy",
    stem_en: "A 2x2 grid of shapes. Top row: one dot, two dots. Bottom row: three dots, ?. Reading the grid left-to-right then top-to-bottom, the number of dots increases by one each cell. What belongs in the empty bottom-right cell?",
    options_en: ["Four dots", "Three dots", "Two dots", "Five dots"], correct_index: 0,
    stem_ar: "شبكة من الأشكال بحجم 2×2. الصف العلوي: نقطة واحدة، نقطتان. الصف السفلي: ثلاث نقاط، ؟. عند قراءة الشبكة من اليسار إلى اليمين ثم من الأعلى إلى الأسفل، يزداد عدد النقاط بمقدار واحد في كل خانة. ما الذي يجب أن يكون في الخانة الفارغة أسفل اليمين؟",
    options_ar: ["أربع نقاط", "ثلاث نقاط", "نقطتان", "خمس نقاط"],
    rationale_en: "The sequence is 1, 2, 3, so the next cell is 4 dots. 'Three dots' repeats the previous cell. 'Two dots' goes backward. 'Five dots' skips 4.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "easy",
    stem_en: "A 2x2 grid. Top row: an upward-pointing arrow, a rightward-pointing arrow. Bottom row: a downward-pointing arrow, ?. Moving through the grid, each arrow rotates 90 degrees clockwise from the one before. What belongs in the empty cell?",
    options_en: ["A leftward-pointing arrow", "An upward-pointing arrow", "A downward-pointing arrow", "A rightward-pointing arrow"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2. الصف العلوي: سهم يشير إلى الأعلى، سهم يشير إلى اليمين. الصف السفلي: سهم يشير إلى الأسفل، ؟. عند التنقل عبر الشبكة، يدور كل سهم 90 درجة في اتجاه عقارب الساعة بالنسبة للسهم الذي قبله. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["سهم يشير إلى اليسار", "سهم يشير إلى الأعلى", "سهم يشير إلى الأسفل", "سهم يشير إلى اليمين"],
    rationale_en: "The rotation is up → right → down, so the next 90-degree clockwise step is left. 'Up' restarts the cycle. 'Down' repeats the previous cell. 'Right' goes back one step.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "easy",
    stem_en: "A 2x2 grid of circles. Top row: a fully white circle, a circle with its left half shaded. Bottom row: a fully shaded circle, ?. In each cell the shading grows, then the pattern repeats: white, half, full, then back to white. What belongs in the empty cell?",
    options_en: ["A fully white circle", "A fully shaded circle", "A circle with its left half shaded", "A circle with its right half shaded"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2 من الدوائر. الصف العلوي: دائرة بيضاء بالكامل، دائرة نصفها الأيسر مظلّل. الصف السفلي: دائرة مظلّلة بالكامل، ؟. في كل خانة يزداد التظليل، ثم يتكرر النمط: أبيض، نصف، كامل، ثم يعود إلى أبيض. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["دائرة بيضاء بالكامل", "دائرة مظلّلة بالكامل", "دائرة نصفها الأيسر مظلّل", "دائرة نصفها الأيمن مظلّل"],
    rationale_en: "The cycle white → half → full repeats, so after full it returns to white. 'Fully shaded' repeats the previous cell. 'Left half shaded' goes backward. 'Right half shaded' is a state that never appears.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "medium",
    stem_en: "A 2x2 grid. Top row: a small square, a large square. Bottom row: a small triangle, ?. Across each row the shape stays the same but grows from small to large; down each column the size stays the same but the shape changes. What belongs in the empty cell?",
    options_en: ["A large triangle", "A small triangle", "A large square", "A small square"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2. الصف العلوي: مربع صغير، مربع كبير. الصف السفلي: مثلث صغير، ؟. عبر كل صف يبقى الشكل نفسه لكنه يكبر من صغير إلى كبير؛ وفي كل عمود يبقى الحجم نفسه بينما يتغير الشكل. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["مثلث كبير", "مثلث صغير", "مربع كبير", "مربع صغير"],
    rationale_en: "The row keeps the triangle shape and enlarges it, so the cell is a large triangle. 'Small triangle' ignores the growth. 'Large square' violates the column rule. 'Small square' breaks both rules.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "medium",
    stem_en: "A 2x2 grid. Top row: a circle containing one star, a circle containing two stars. Bottom row: a square containing one star, ?. Left-to-right the number of inner stars increases by one; top-to-bottom the outer shape changes from circle to square while the star count is inherited from the cell above. What belongs in the empty cell?",
    options_en: ["A square containing two stars", "A circle containing two stars", "A square containing one star", "A square containing three stars"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2. الصف العلوي: دائرة بداخلها نجمة واحدة، دائرة بداخلها نجمتان. الصف السفلي: مربع بداخله نجمة واحدة، ؟. من اليسار إلى اليمين يزداد عدد النجوم الداخلية بمقدار واحد؛ ومن الأعلى إلى الأسفل يتغير الشكل الخارجي من دائرة إلى مربع بينما يُستمد عدد النجوم من الخانة التي فوقها. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["مربع بداخله نجمتان", "دائرة بداخلها نجمتان", "مربع بداخله نجمة واحدة", "مربع بداخله ثلاث نجوم"],
    rationale_en: "The outer shape must be a square (row rule) and the star count goes 1 → 2, giving a square with two stars. 'Circle with two stars' uses the wrong outer shape. 'Square with one star' fails to increase the count. 'Square with three stars' overshoots.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "medium",
    stem_en: "A 2x2 grid of clock-like faces showing a single hand. Top row: hand pointing to 12, hand pointing to 3. Bottom row: hand pointing to 6, ?. Reading left-to-right then top-to-bottom, the hand moves a quarter-turn clockwise (12 to 3 to 6 to 9) each step. What belongs in the empty cell?",
    options_en: ["Hand pointing to 9", "Hand pointing to 12", "Hand pointing to 3", "Hand pointing to 6"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2 من أوجه تشبه الساعة يظهر فيها عقرب واحد. الصف العلوي: عقرب يشير إلى الرقم 12، عقرب يشير إلى الرقم 3. الصف السفلي: عقرب يشير إلى الرقم 6، ؟. عند القراءة من اليسار إلى اليمين ثم من الأعلى إلى الأسفل، يتحرك العقرب ربع دورة في اتجاه عقارب الساعة (12 ثم 3 ثم 6 ثم 9) في كل خطوة. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["عقرب يشير إلى الرقم 9", "عقرب يشير إلى الرقم 12", "عقرب يشير إلى الرقم 3", "عقرب يشير إلى الرقم 6"],
    rationale_en: "The quarter-turn sequence 12, 3, 6 continues to 9. 'Pointing to 12' restarts the cycle. 'Pointing to 3' skips backward. 'Pointing to 6' repeats the previous cell.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "medium",
    stem_en: "A 2x2 grid. Top row: a circle with a dot inside, a circle with no dot. Bottom row: a triangle with a dot inside, ?. Along each row the inner dot is present in the first cell and removed in the second; the outer shape stays constant within its row. What belongs in the empty cell?",
    options_en: ["A triangle with no dot", "A triangle with a dot inside", "A circle with no dot", "A square with no dot"], correct_index: 0,
    stem_ar: "شبكة بحجم 2×2. الصف العلوي: دائرة بداخلها نقطة، دائرة بلا نقطة. الصف السفلي: مثلث بداخله نقطة، ؟. على امتداد كل صف تكون النقطة الداخلية موجودة في الخانة الأولى ومحذوفة في الثانية؛ ويبقى الشكل الخارجي ثابتًا داخل صفه. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["مثلث بلا نقطة", "مثلث بداخله نقطة", "دائرة بلا نقطة", "مربع بلا نقطة"],
    rationale_en: "The row rule removes the dot while keeping the triangle, giving a triangle with no dot. 'Triangle with a dot' fails to remove it. 'Circle with no dot' changes the shape. 'Square with no dot' introduces a shape that never appears.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "hard",
    stem_en: "A 3x3 grid. Row 1: one line, two lines, three lines. Row 2: two lines, three lines, four lines. Row 3: three lines, four lines, ?. In every row the count rises by one left-to-right, and each row starts one higher than the row above. What belongs in the empty bottom-right cell?",
    options_en: ["Five lines", "Four lines", "Six lines", "Three lines"], correct_index: 0,
    stem_ar: "شبكة بحجم 3×3. الصف الأول: خط واحد، خطان، ثلاثة خطوط. الصف الثاني: خطان، ثلاثة خطوط، أربعة خطوط. الصف الثالث: ثلاثة خطوط، أربعة خطوط، ؟. في كل صف يرتفع العدد بمقدار واحد من اليسار إلى اليمين، ويبدأ كل صف بعدد أعلى بواحد من الصف الذي فوقه. ما الذي يجب أن يكون في الخانة الفارغة أسفل اليمين؟",
    options_ar: ["خمسة خطوط", "أربعة خطوط", "ستة خطوط", "ثلاثة خطوط"],
    rationale_en: "Row 3 runs 3, 4, so the third cell is 5, which also fits the column pattern (3, 4, 5). 'Four lines' repeats the middle cell. 'Six lines' over-counts by two. 'Three lines' restarts the row.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "hard",
    stem_en: "A 3x3 grid combining two features: shape (circle, square, triangle) and the number of small dots beside it (1, 2, 3). Row 1: circle-1dot, square-2dots, triangle-3dots. Row 2: square-3dots, triangle-1dot, circle-2dots. Row 3: triangle-2dots, circle-3dots, ?. In each row all three shapes appear once and all three dot-counts appear once; the same is true down each column. What belongs in the empty cell?",
    options_en: ["Square with 1 dot", "Triangle with 1 dot", "Square with 3 dots", "Circle with 1 dot"], correct_index: 0,
    stem_ar: "شبكة بحجم 3×3 تجمع بين خاصيتين: الشكل (دائرة، مربع، مثلث) وعدد النقاط الصغيرة بجانبه (1، 2، 3). الصف الأول: دائرة و1 نقطة، مربع و2 نقطة، مثلث و3 نقاط. الصف الثاني: مربع و3 نقاط، مثلث و1 نقطة، دائرة و2 نقطة. الصف الثالث: مثلث و2 نقطة، دائرة و3 نقاط، ؟. في كل صف يظهر كل شكل مرة واحدة ويظهر كل عدد من النقاط مرة واحدة؛ والأمر نفسه في كل عمود. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["مربع مع نقطة واحدة", "مثلث مع نقطة واحدة", "مربع مع ثلاث نقاط", "دائرة مع نقطة واحدة"],
    rationale_en: "Row 3 already has triangle and circle, so the missing shape is square; it has 2 and 3 dots, so the missing count is 1; the last column confirms square-1dot. 'Triangle with 1 dot' repeats a shape in the row. 'Square with 3 dots' repeats a count already in the row and column. 'Circle with 1 dot' repeats the circle.",
  },
  {
    subtest: "inductive", facet: "ind_matrix", difficulty: "hard",
    stem_en: "A 3x3 grid of squares, each divided into four small cells with some cells shaded. Reading left-to-right in every row, one additional small cell becomes shaded each step, and the shading fills in clockwise starting from the top-left small cell. Row 3 shows: one shaded (top-left), two shaded (top-left and top-right), ?. What belongs in the empty cell?",
    options_en: ["Three shaded: top-left, top-right, and bottom-right", "Three shaded: top-left, top-right, and bottom-left", "Two shaded: top-left and bottom-right", "Four shaded: all small cells"], correct_index: 0,
    stem_ar: "شبكة بحجم 3×3 من المربعات، كل مربع مقسوم إلى أربع خانات صغيرة مع تظليل بعضها. عند القراءة من اليسار إلى اليمين في كل صف، تُظلَّل خانة صغيرة إضافية واحدة في كل خطوة، ويمتلئ التظليل في اتجاه عقارب الساعة بدءًا من الخانة الصغيرة أعلى اليسار. يعرض الصف الثالث: خانة واحدة مظلّلة (أعلى اليسار)، خانتان مظلّلتان (أعلى اليسار وأعلى اليمين)، ؟. ما الذي يجب أن يكون في الخانة الفارغة؟",
    options_ar: ["ثلاث خانات مظلّلة: أعلى اليسار وأعلى اليمين وأسفل اليمين", "ثلاث خانات مظلّلة: أعلى اليسار وأعلى اليمين وأسفل اليسار", "خانتان مظلّلتان: أعلى اليسار وأسفل اليمين", "أربع خانات مظلّلة: جميع الخانات الصغيرة"],
    rationale_en: "Clockwise from top-left the order is top-left, top-right, bottom-right, so the third step adds bottom-right. The option ending in bottom-left goes counter-clockwise. 'Two shaded' fails to add the third cell. 'Four shaded' adds two cells at once.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "easy",
    stem_en: "All robins are birds. All birds have feathers. Which conclusion necessarily follows?",
    options_en: ["All robins have feathers.", "All birds are robins.", "Some feathered things are not birds.", "No robins have feathers."], correct_index: 0,
    stem_ar: "كل أبي الحناء طيور. كل الطيور لها ريش. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["كل أبي الحناء له ريش.", "كل الطيور من أبي الحناء.", "بعض الأشياء ذات الريش ليست طيوراً.", "لا شيء من أبي الحناء له ريش."],
    rationale_en: "Valid Barbara syllogism: robins ⊆ birds ⊆ feathered, so robins ⊆ feathered (index 0). 'All birds are robins' illegally reverses the first premise. 'Some feathered things are not birds' is not entailed. 'No robins have feathers' contradicts the chain.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "easy",
    stem_en: "No reptiles are mammals. All snakes are reptiles. Which conclusion necessarily follows?",
    options_en: ["No snakes are mammals.", "All mammals are snakes.", "Some snakes are mammals.", "All reptiles are snakes."], correct_index: 0,
    stem_ar: "لا شيء من الزواحف من الثدييات. كل الأفاعي زواحف. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا شيء من الأفاعي من الثدييات.", "كل الثدييات أفاعٍ.", "بعض الأفاعي من الثدييات.", "كل الزواحف أفاعٍ."],
    rationale_en: "Valid Celarent: snakes ⊆ reptiles and reptiles are disjoint from mammals, so snakes are disjoint from mammals (index 0). 'Some snakes are mammals' contradicts this; the other two illegally reverse a premise.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "easy",
    stem_en: "All roses are flowers. Some flowers are red. Which conclusion necessarily follows?",
    options_en: ["No valid conclusion follows.", "Some roses are red.", "All red things are roses.", "All flowers are roses."], correct_index: 0,
    stem_ar: "كل الورود أزهار. بعض الأزهار حمراء. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا يتبع أي استنتاج صحيح.", "بعض الورود حمراء.", "كل الأشياء الحمراء ورود.", "كل الأزهار ورود."],
    rationale_en: "The red flowers need not be roses, so nothing follows about roses being red (index 0). 'Some roses are red' commits exactly this error; the last two illegally reverse the first premise.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "medium",
    stem_en: "All cups on the shelf are green. Some green things are made of glass. Which conclusion necessarily follows?",
    options_en: ["No valid conclusion follows.", "Some cups on the shelf are made of glass.", "All glass things are cups on the shelf.", "No cup on the shelf is made of glass."], correct_index: 0,
    stem_ar: "كل الأكواب على الرف خضراء. بعض الأشياء الخضراء مصنوعة من الزجاج. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا يتبع أي استنتاج صحيح.", "بعض الأكواب على الرف مصنوعة من الزجاج.", "كل الأشياء الزجاجية أكواب على الرف.", "لا شيء من الأكواب على الرف مصنوع من الزجاج."],
    rationale_en: "Cups are a subset of green things, but the glass green things could lie entirely outside that subset, so no cup–glass link is forced (index 0). 'Some cups are glass' and 'No cup is glass' are both unproven; 'All glass things are cups' reverses the premise.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "medium",
    stem_en: "All teachers at the school ride bicycles. Some people who ride bicycles wear hats. No hat-wearer at the event was late. Which conclusion necessarily follows?",
    options_en: ["No valid conclusion follows.", "Some teachers at the school wear hats.", "All teachers at the school were late.", "No teacher at the school rides a bicycle."], correct_index: 0,
    stem_ar: "كل المعلمين في المدرسة يركبون الدراجات. بعض راكبي الدراجات يرتدون القبعات. لا شيء من مرتدي القبعات في الفعالية كان متأخراً. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا يتبع أي استنتاج صحيح.", "بعض المعلمين في المدرسة يرتدون القبعات.", "كل المعلمين في المدرسة كانوا متأخرين.", "لا شيء من المعلمين في المدرسة يركب الدراجة."],
    rationale_en: "The only firm chain is teachers ⊆ bicycle-riders; the hat-wearing riders need not include any teacher, so nothing follows (index 0). 'Some teachers wear hats' assumes the hat-wearers are teachers; the others contradict or overreach the premises.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "medium",
    stem_en: "No item in the box is fragile. All the mugs are in the box. Which conclusion necessarily follows?",
    options_en: ["No mug is fragile.", "All fragile things are mugs.", "Some mugs are fragile.", "All items in the box are mugs."], correct_index: 0,
    stem_ar: "لا شيء في الصندوق قابل للكسر. كل الأكواب في الصندوق. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا شيء من الأكواب قابل للكسر.", "كل الأشياء القابلة للكسر أكواب.", "بعض الأكواب قابلة للكسر.", "كل ما في الصندوق أكواب."],
    rationale_en: "Mugs ⊆ box-items and box-items are all non-fragile, so mugs are non-fragile (index 0) by Celarent. 'Some mugs are fragile' contradicts this; 'All items in the box are mugs' reverses premise two; 'All fragile things are mugs' is unsupported.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "medium",
    stem_en: "Some visitors to the park are children. All children like ice cream. Which conclusion necessarily follows?",
    options_en: ["Some visitors to the park like ice cream.", "All visitors to the park are children.", "All visitors to the park like ice cream.", "No visitor to the park likes ice cream."], correct_index: 0,
    stem_ar: "بعض زوار الحديقة أطفال. كل الأطفال يحبون المثلجات. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["بعض زوار الحديقة يحبون المثلجات.", "كل زوار الحديقة أطفال.", "كل زوار الحديقة يحبون المثلجات.", "لا شيء من زوار الحديقة يحب المثلجات."],
    rationale_en: "Valid Darii: some visitors are children, and all children like ice cream, so those visitors like ice cream (index 0). 'All visitors like ice cream' overreaches; 'All visitors are children' reverses the particular premise; the last contradicts the derived overlap.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "hard",
    stem_en: "All members of the club can swim. Some people who can swim cannot run fast. No one who cannot run fast joined the race. Which conclusion necessarily follows?",
    options_en: ["No valid conclusion follows.", "Some members of the club did not join the race.", "No member of the club joined the race.", "All members of the club joined the race."], correct_index: 0,
    stem_ar: "كل أعضاء النادي يجيدون السباحة. بعض من يجيدون السباحة لا يجيدون الجري السريع. لا شيء ممن لا يجيدون الجري السريع اشترك في السباق. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["لا يتبع أي استنتاج صحيح.", "بعض أعضاء النادي لم يشتركوا في السباق.", "لا شيء من أعضاء النادي اشترك في السباق.", "كل أعضاء النادي اشتركوا في السباق."],
    rationale_en: "Members ⊆ swimmers, and only some swimmers cannot run fast; those slow swimmers need not be members, so no member is forced into the 'did-not-join' set (index 0). 'Some members did not join' assumes the slow swimmers are members; the others overstate or are unsupported.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "hard",
    stem_en: "All the tools in the drawer are metal. No wooden object is metal. Some objects on the table are wooden. Which conclusion necessarily follows?",
    options_en: ["Some objects on the table are not tools in the drawer.", "No object on the table is a tool in the drawer.", "All tools in the drawer are on the table.", "Some tools in the drawer are wooden."], correct_index: 0,
    stem_ar: "كل الأدوات في الدرج معدنية. لا شيء من الأشياء الخشبية معدني. بعض الأشياء على الطاولة خشبية. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["بعض الأشياء على الطاولة ليست أدوات في الدرج.", "لا شيء من الأشياء على الطاولة أداة في الدرج.", "كل الأدوات في الدرج على الطاولة.", "بعض الأدوات في الدرج خشبية."],
    rationale_en: "The wooden table-objects are non-metal, and every drawer-tool is metal, so those wooden objects cannot be drawer-tools (index 0). 'No object on the table is a tool' overreaches (only the wooden ones are excluded); 'All tools are on the table' is unsupported; 'Some tools are wooden' contradicts the metal/wooden disjointness.",
  },
  {
    subtest: "deductive", facet: "ded_syllogism", difficulty: "hard",
    stem_en: "No book on the top shelf is old. All the diaries are old. Some diaries are locked. Which conclusion necessarily follows?",
    options_en: ["Some locked things are not books on the top shelf.", "No locked thing is a diary.", "Some books on the top shelf are locked.", "All old things are diaries."], correct_index: 0,
    stem_ar: "لا شيء من الكتب على الرف العلوي قديم. كل المفكرات قديمة. بعض المفكرات مقفلة. أي استنتاج يتبع بالضرورة؟",
    options_ar: ["بعض الأشياء المقفلة ليست كتباً على الرف العلوي.", "لا شيء من الأشياء المقفلة مفكرة.", "بعض الكتب على الرف العلوي مقفلة.", "كل الأشياء القديمة مفكرات."],
    rationale_en: "Some diaries are locked; all diaries are old; top-shelf books are never old. So those locked diaries are old, hence not top-shelf books (index 0). 'No locked thing is a diary' contradicts the premise; 'Some top-shelf books are locked' is unsupported; 'All old things are diaries' reverses the second premise.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "easy",
    stem_en: "If the light is green, then the gate is open. The light is green. What follows?",
    options_en: ["The gate is open.", "The gate is closed.", "The light is red.", "Nothing can be concluded."], correct_index: 0,
    stem_ar: "إذا كان الضوء أخضر، فإن البوابة مفتوحة. الضوء أخضر. ماذا يترتب على ذلك؟",
    options_ar: ["البوابة مفتوحة.", "البوابة مغلقة.", "الضوء أحمر.", "لا يمكن استنتاج أي شيء."],
    rationale_en: "Modus ponens: given 'if P then Q' and P, Q must hold, so the gate is open (index 0). Option 1 contradicts the conclusion; option 2 contradicts the stated fact; option 3 is wrong because a firm conclusion does follow.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "easy",
    stem_en: "If it is raining, then the ground is wet. It is raining. What must be true?",
    options_en: ["The ground is wet.", "The ground is dry.", "It is not raining.", "It is sunny."], correct_index: 0,
    stem_ar: "إذا كانت السماء تمطر، فإن الأرض مبللة. السماء تمطر. ما الذي يجب أن يكون صحيحاً؟",
    options_ar: ["الأرض مبللة.", "الأرض جافة.", "السماء لا تمطر.", "الجو مشمس."],
    rationale_en: "Modus ponens forces 'the ground is wet' (index 0). Option 1 contradicts that conclusion; option 2 denies the given fact; option 3 is unrelated and unsupported.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "easy",
    stem_en: "If the box is a cube, then it has six faces. This box does NOT have six faces. What follows?",
    options_en: ["The box is not a cube.", "The box is a cube.", "The box has five faces.", "Nothing can be concluded."], correct_index: 0,
    stem_ar: "إذا كان الصندوق مكعباً، فإن له ستة أوجه. هذا الصندوق ليس له ستة أوجه. ماذا يترتب على ذلك؟",
    options_ar: ["الصندوق ليس مكعباً.", "الصندوق مكعب.", "للصندوق خمسة أوجه.", "لا يمكن استنتاج أي شيء."],
    rationale_en: "Modus tollens: 'if P then Q' with 'not Q' forces 'not P' (index 0). Option 1 contradicts it; option 2 asserts the opposite conclusion; option 3 gives an unsupported specific face count.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "medium",
    stem_en: "If Layla went for a walk, then she took her keys. Layla did NOT take her keys. What can be concluded?",
    options_en: ["Layla did not go for a walk.", "Layla went for a walk.", "Layla lost her keys.", "Layla stayed home all day."], correct_index: 0,
    stem_ar: "إذا خرجت ليلى للمشي، فإنها أخذت مفاتيحها. ليلى لم تأخذ مفاتيحها. ما الذي يمكن استنتاجه؟",
    options_ar: ["ليلى لم تخرج للمشي.", "ليلى خرجت للمشي.", "ليلى فقدت مفاتيحها.", "ليلى بقيت في المنزل طوال اليوم."],
    rationale_en: "Modus tollens: from 'if walk then keys' and 'not keys', deduce 'not walk' (index 0). Option 1 asserts the opposite; option 2 introduces losing keys, not stated; option 3 overreaches (not walking ≠ staying home all day).",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "medium",
    stem_en: "If a shape is a square, then it has four sides. A certain shape has four sides. What validly follows?",
    options_en: ["Nothing certain follows about whether it is a square.", "The shape is a square.", "The shape is not a square.", "The shape is a triangle."], correct_index: 0,
    stem_ar: "إذا كان الشكل مربعاً، فإن له أربعة أضلاع. شكل معين له أربعة أضلاع. ما الذي يترتب على ذلك بشكل صحيح؟",
    options_ar: ["لا يترتب شيء مؤكد حول ما إذا كان مربعاً.", "الشكل مربع.", "الشكل ليس مربعاً.", "الشكل مثلث."],
    rationale_en: "Affirming the consequent: knowing Q (four sides) does not establish P (square), since rectangles also have four sides, so nothing certain follows (index 0). Option 1 commits the fallacy; option 2 is unsupported; option 3 contradicts the given fact (triangles have three sides).",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "medium",
    stem_en: "If the alarm rings, then everyone leaves the building. Right now, some people are still inside the building. What follows?",
    options_en: ["The alarm is not ringing.", "The alarm is ringing.", "Everyone left the building.", "The building is empty."], correct_index: 0,
    stem_ar: "إذا دق جرس الإنذار، فإن الجميع يغادرون المبنى. في هذه اللحظة، لا يزال بعض الناس داخل المبنى. ماذا يترتب على ذلك؟",
    options_ar: ["جرس الإنذار لا يدق.", "جرس الإنذار يدق.", "الجميع غادروا المبنى.", "المبنى فارغ."],
    rationale_en: "'Some people still inside' makes the consequent false; by modus tollens the antecedent is false, so the alarm is not ringing (index 0). Option 1 asserts the opposite; options 2 and 3 contradict the stated fact.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "medium",
    stem_en: "If the jar is full, then no more marbles fit. More marbles fit in the jar. What can be concluded?",
    options_en: ["The jar is not full.", "The jar is full.", "The jar is empty.", "There are exactly ten marbles in the jar."], correct_index: 0,
    stem_ar: "إذا كان الوعاء ممتلئاً، فلا يمكن إضافة المزيد من الكُرات. يمكن إضافة المزيد من الكُرات في الوعاء. ما الذي يمكن استنتاجه؟",
    options_ar: ["الوعاء ليس ممتلئاً.", "الوعاء ممتلئ.", "الوعاء فارغ.", "يوجد بالضبط عشر كُرات في الوعاء."],
    rationale_en: "'More marbles fit' denies the consequent; by modus tollens the antecedent is false, so the jar is not full (index 0). Option 1 asserts the opposite; option 2 overreaches (not full ≠ empty); option 3 states an unprovided count.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "hard",
    stem_en: "If a card shows a circle, then its back is shaded. You see a card whose back is NOT shaded. Which statement is guaranteed true?",
    options_en: ["The card does not show a circle.", "The card shows a circle.", "Every unshaded card shows a square.", "If the back is shaded, the front shows a circle."], correct_index: 0,
    stem_ar: "إذا أظهرت البطاقة دائرة، فإن ظهرها مظلّل. ترى بطاقة ظهرها ليس مظلّلاً. أي عبارة مضمونة الصحة؟",
    options_ar: ["البطاقة لا تُظهر دائرة.", "البطاقة تُظهر دائرة.", "كل بطاقة غير مظلّلة تُظهر مربعاً.", "إذا كان الظهر مظلّلاً، فإن الوجه يُظهر دائرة."],
    rationale_en: "Modus tollens on 'if circle then shaded back' with 'back not shaded' forces 'not circle' (index 0). Option 1 asserts the opposite; option 2 adds an unstated square claim; option 3 is the converse of the rule, which does not follow.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "hard",
    stem_en: "If Omar takes the early bus, then he arrives before noon. If he arrives before noon, then he eats lunch at the park. Omar did NOT eat lunch at the park. What follows?",
    options_en: ["Omar did not take the early bus.", "Omar took the early bus.", "Omar arrived before noon.", "Omar took a later bus and still arrived before noon."], correct_index: 0,
    stem_ar: "إذا ركب عمر الحافلة المبكرة، فإنه يصل قبل الظهر. وإذا وصل قبل الظهر، فإنه يتناول الغداء في الحديقة. عمر لم يتناول الغداء في الحديقة. ماذا يترتب على ذلك؟",
    options_ar: ["عمر لم يركب الحافلة المبكرة.", "عمر ركب الحافلة المبكرة.", "عمر وصل قبل الظهر.", "عمر ركب حافلة لاحقة ووصل قبل الظهر رغم ذلك."],
    rationale_en: "Chaining gives 'if early bus then lunch at park'; since he did not eat at the park, modus tollens yields 'not early bus' (index 0). Working backward, 'not lunch at park' also forces 'not arrived before noon', so options 2 and 3 contradict a derived fact; option 1 asserts the opposite conclusion.",
  },
  {
    subtest: "deductive", facet: "ded_conditional", difficulty: "hard",
    stem_en: "Every card with a vowel on one side has an even number on the other side. A card is showing an odd number. What must be true of that card?",
    options_en: ["It does not have a vowel on its other side.", "It has a vowel on its other side.", "It has a consonant on the other side and shows an even number.", "Nothing can be concluded about it."], correct_index: 0,
    stem_ar: "كل بطاقة تحمل حرفاً متحركاً على أحد وجهيها تحمل رقماً زوجياً على الوجه الآخر. تُظهر بطاقة رقماً فردياً. ما الذي يجب أن يكون صحيحاً بشأن هذه البطاقة؟",
    options_ar: ["لا تحمل حرفاً متحركاً على وجهها الآخر.", "تحمل حرفاً متحركاً على وجهها الآخر.", "تحمل حرفاً ساكناً على الوجه الآخر وتُظهر رقماً زوجياً.", "لا يمكن استنتاج أي شيء بشأنها."],
    rationale_en: "The rule is 'vowel ⇒ even number'. The card shows an odd (not even) number, so by modus tollens it cannot have a vowel on the other side (index 0). Option 1 asserts the opposite; option 2 contradicts the given odd number; option 3 is wrong because a definite conclusion does follow.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "easy",
    stem_en: "Four friends stand in a single line for a photo. Lena is directly to the left of Omar. Priya is directly to the left of Lena. Sam is directly to the left of Priya. Reading the line from left to right, who is in the second position?",
    options_en: ["Sam", "Priya", "Lena", "Omar"], correct_index: 1,
    stem_ar: "يقف أربعة أصدقاء في صف واحد لالتقاط صورة. لينا على يسار عمر مباشرة. بريا على يسار لينا مباشرة. سام على يسار بريا مباشرة. عند قراءة الصف من اليسار إلى اليمين، من في الموضع الثاني؟",
    options_ar: ["سام", "بريا", "لينا", "عمر"],
    rationale_en: "The constraints fix the order left-to-right as Sam, Priya, Lena, Omar. Position two is Priya (index 1). Sam is first, Lena third, Omar fourth.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "easy",
    stem_en: "Three books are stacked in a pile. The red book is somewhere above the green book. The blue book is at the very top, above both others. Which book is at the bottom of the pile?",
    options_en: ["The blue book", "The red book", "The green book", "Cannot be determined"], correct_index: 2,
    stem_ar: "توضع ثلاثة كتب في كومة فوق بعضها. الكتاب الأحمر في مكان ما فوق الكتاب الأخضر. الكتاب الأزرق في القمة تماماً، فوق الكتابين الآخرين. أي كتاب في أسفل الكومة؟",
    options_ar: ["الكتاب الأزرق", "الكتاب الأحمر", "الكتاب الأخضر", "لا يمكن تحديده"],
    rationale_en: "Blue is top and red is above green, so top-to-bottom is blue, red, green. The bottom book is green (index 2). Blue is the top; red is the middle; the order is fully fixed, so 'Cannot be determined' is wrong.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "easy",
    stem_en: "Five runners finish a race one after another with no ties. Maria finishes immediately before Tom. Tom finishes immediately before Nina. Nina finishes immediately before Karim. Karim finishes immediately before Yusuf. Who finishes in the middle (third) position?",
    options_en: ["Tom", "Nina", "Karim", "Maria"], correct_index: 1,
    stem_ar: "يُنهي خمسة عدّائين السباق واحداً تلو الآخر دون تعادل. تُنهي ماريا قبل توم مباشرة. يُنهي توم قبل نينا مباشرة. تُنهي نينا قبل كريم مباشرة. يُنهي كريم قبل يوسف مباشرة. من يُنهي في الموضع الأوسط (الثالث)؟",
    options_ar: ["توم", "نينا", "كريم", "ماريا"],
    rationale_en: "The chain fixes the order Maria, Tom, Nina, Karim, Yusuf. The third finisher is Nina (index 1). Maria is first, Tom second, Karim fourth.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "medium",
    stem_en: "Four cups are lined up on a shelf from left to right. The white cup is somewhere to the left of the black cup. The grey cup is at the far right end. The white cup is not at the far left end. Which cup is at the far left end?",
    options_en: ["The white cup", "The black cup", "The grey cup", "The green cup"], correct_index: 3,
    stem_ar: "توضع أربعة أكواب في صف على رفّ من اليسار إلى اليمين. الكوب الأبيض في مكان ما على يسار الكوب الأسود. الكوب الرمادي في أقصى اليمين. الكوب الأبيض ليس في أقصى اليسار. أي كوب في أقصى اليسار؟",
    options_ar: ["الكوب الأبيض", "الكوب الأسود", "الكوب الرمادي", "الكوب الأخضر"],
    rationale_en: "The four cups are white, black, grey, green. Grey is fixed at position 4. White is not at position 1, and black (being right of white) cannot be at position 1 either, so only green can occupy the far left (index 3).",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "medium",
    stem_en: "Five children sit in a row of five chairs numbered 1 to 5 from left to right. Dana sits in chair 3. Ravi sits immediately to Dana's right. Sofia sits immediately to Dana's left. Mia sits immediately next to Sofia. Leo takes the remaining chair. Who sits in chair 5?",
    options_en: ["Ravi", "Leo", "Mia", "Sofia"], correct_index: 1,
    stem_ar: "يجلس خمسة أطفال في صف من خمسة كراسي مرقّمة من 1 إلى 5 من اليسار إلى اليمين. تجلس دانا في الكرسي 3. يجلس رافي على يمين دانا مباشرة. تجلس صوفيا على يسار دانا مباشرة. تجلس ميا بجوار صوفيا مباشرة. يأخذ ليو الكرسي المتبقي. من يجلس في الكرسي 5؟",
    options_ar: ["رافي", "ليو", "ميا", "صوفيا"],
    rationale_en: "Ravi is in chair 4 and Sofia in chair 2. Mia sits immediately next to Sofia; chair 3 is Dana's, so Mia must be in chair 1. That leaves chair 5 for Leo (index 1). Ravi is chair 4, Sofia chair 2, Mia chair 1.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "medium",
    stem_en: "Four parcels are delivered one at a time during the day: a box, a tube, an envelope, and a crate. The envelope is delivered at some point before the crate. The box is delivered first. The tube is delivered immediately after the box. Which parcel is delivered last?",
    options_en: ["The box", "The tube", "The envelope", "The crate"], correct_index: 3,
    stem_ar: "تُسلَّم أربعة طرود واحداً تلو الآخر خلال اليوم: صندوق، وأنبوب، ومظروف، وقفص. يُسلَّم المظروف في وقت ما قبل القفص. يُسلَّم الصندوق أولاً. يُسلَّم الأنبوب بعد الصندوق مباشرة. أي طرد يُسلَّم أخيراً؟",
    options_ar: ["الصندوق", "الأنبوب", "المظروف", "القفص"],
    rationale_en: "Box is first and tube immediately after, so positions 1 and 2 are box then tube. The envelope and crate fill 3 and 4 with envelope before crate, so envelope is third and crate is last (index 3).",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "medium",
    stem_en: "Five people queue at a door in a single file. Hana is ahead of Ivan. Ivan is ahead of Jad. Hana is exactly in the middle of the line of five. Two people, Nour and Basil, fill the remaining places, with Nour ahead of Basil and both ahead of Hana. Counting from the front, who is at the very front of the queue?",
    options_en: ["Hana", "Ivan", "Nour", "Basil"], correct_index: 2,
    stem_ar: "يصطف خمسة أشخاص عند باب في صف واحد. هَنا أمام إيفان. إيفان أمام جاد. هَنا في منتصف الصف تماماً من بين الخمسة. يملأ شخصان، نور وباسل، المواضع المتبقية، بحيث يكون نور أمام باسل وكلاهما أمام هَنا. بالعدّ من المقدمة، من في مقدمة الصف تماماً؟",
    options_ar: ["هَنا", "إيفان", "نور", "باسل"],
    rationale_en: "Hana is in the middle of five, so position 3. Nour and Basil are both ahead of Hana with Nour ahead of Basil, so they take positions 1 and 2 as Nour then Basil; Ivan and Jad follow at 4 and 5. The front is Nour (index 2).",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "hard",
    stem_en: "Five houses stand in a row along a street, numbered 1 to 5. The tallest house is not at either end. The garden house is immediately left of the tallest house. The stone house is at position 5. The garden house is somewhere to the right of position 1. Exactly one house sits between the garden house and the stone house. At which position is the garden house?",
    options_en: ["Position 2", "Position 3", "Position 4", "Position 1"], correct_index: 1,
    stem_ar: "تقف خمسة منازل في صف على طول شارع، مرقّمة من 1 إلى 5. المنزل الأطول ليس في أي من الطرفين. منزل الحديقة على يسار المنزل الأطول مباشرة. المنزل الحجري في الموضع 5. منزل الحديقة في مكان ما على يمين الموضع 1. يوجد منزل واحد بالضبط بين منزل الحديقة والمنزل الحجري. في أي موضع يقع منزل الحديقة؟",
    options_ar: ["الموضع 2", "الموضع 3", "الموضع 4", "الموضع 1"],
    rationale_en: "The stone house is at 5, and exactly one house lies between the garden house and it, so the garden house is at position 3 (only position 4 between them). This is consistent: the tallest is immediately right at position 4 (not an end) and position 3 is right of position 1. Position 2 leaves two houses between it and 5; position 4 forces the tallest to end/stone position 5; position 1 is excluded. Only position 3 (index 1) fits.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "hard",
    stem_en: "Four items are placed on four shelves stacked vertically, one item per shelf, labelled from bottom (1) to top (4): a lamp, a clock, a vase, and a plant. The clock is higher than the lamp. The vase is directly above the plant. The lamp is not on the bottom shelf. Which item is on the bottom shelf?",
    options_en: ["The lamp", "The clock", "The vase", "The plant"], correct_index: 3,
    stem_ar: "توضع أربعة أغراض على أربعة رفوف مرتّبة عمودياً، غرض واحد لكل رفّ، مرقّمة من الأسفل (1) إلى الأعلى (4): مصباح، وساعة، ومزهرية، ونبتة. الساعة أعلى من المصباح. المزهرية فوق النبتة مباشرة. المصباح ليس على الرفّ السفلي. أي غرض على الرفّ السفلي؟",
    options_ar: ["المصباح", "الساعة", "المزهرية", "النبتة"],
    rationale_en: "The lamp is not on shelf 1; the clock (higher than the lamp) cannot be on shelf 1 either; the vase (directly above the plant) needs a shelf below it, so it cannot be on shelf 1. Only the plant can be on the bottom (index 3). A consistent full order is plant, vase, lamp, clock.",
  },
  {
    subtest: "deductive", facet: "ded_arrangement", difficulty: "hard",
    stem_en: "Five friends finish a chess tournament ranked 1st (highest) to 5th, with no ties. Hana finishes 1st. Karim finishes last. Sami finishes immediately after Hana. Nadia finishes in the rank immediately after Omar. Who finishes 4th?",
    options_en: ["Omar", "Nadia", "Sami", "Karim"], correct_index: 1,
    stem_ar: "يُنهي خمسة أصدقاء بطولة شطرنج بترتيب من الأول (الأعلى) إلى الخامس دون تعادل. تُنهي هَنا في المركز الأول. يُنهي كريم في المركز الأخير. يُنهي سامي مباشرة بعد هَنا. تحتلّ نادية المركز الذي يلي عمر مباشرة. من يُنهي في المركز الرابع؟",
    options_ar: ["عمر", "نادية", "سامي", "كريم"],
    rationale_en: "Hana is 1st and Sami is immediately after her, so Sami is 2nd. Karim is 5th. That leaves ranks 3 and 4 for Omar and Nadia; since Nadia is immediately after Omar, Omar is 3rd and Nadia is 4th (index 1). Omar is 3rd, Sami 2nd, Karim 5th.",
  },
];
