// AUTO-GENERATED - do not hand-edit. VIFM Fluent receptive bank seed v1.
// 120 vetted CEFR-ramped items (reading + listening x A1-C2 x 10),
// authored to the CEFR anchors then adversarially level-reviewed.
// Loaded by seedFluentBank as status='in_review' pending SME promotion to 'live'.

export type FluentSeedItem = {
  skill: "reading" | "listening";
  cefr: string;
  content: string;
  question: string;
  options: string[];
  correct_index: number;
  explanation_en: string | null;
};

export const FLUENT_SEED_V1: FluentSeedItem[] = [
  {
    skill: "reading", cefr: "A1",
    content: "The office opens at nine o'clock. It closes at five o'clock.",
    question: "What time does the office open?",
    options: ["At five o'clock", "At nine o'clock", "At three o'clock", "At seven o'clock"], correct_index: 1,
    explanation_en: "The text states directly that the office opens at nine o'clock.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "My name is Sara. I am a new bank teller.",
    question: "What is Sara's job?",
    options: ["Bank teller", "Teacher", "Doctor", "Driver"], correct_index: 0,
    explanation_en: "The text says Sara is a new bank teller.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "The meeting is on Monday. It is in Room 3.",
    question: "Where is the meeting?",
    options: ["In Room 5", "In Room 3", "In the cafe", "At home"], correct_index: 1,
    explanation_en: "The text states the meeting is in Room 3.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "Ahmed has ten pens on his desk. He has one computer too.",
    question: "How many pens does Ahmed have?",
    options: ["One", "Five", "Ten", "Twenty"], correct_index: 2,
    explanation_en: "The text says Ahmed has ten pens on his desk.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "The coffee is hot. The water is cold.",
    question: "How is the coffee?",
    options: ["Cold", "Hot", "Old", "Small"], correct_index: 1,
    explanation_en: "The text states directly that the coffee is hot.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "Lisa works in a big office. The office is in the city.",
    question: "Where is the office?",
    options: ["In the city", "In a village", "By the sea", "On a farm"], correct_index: 0,
    explanation_en: "The text says the office is in the city.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "The bank is closed today. It is open tomorrow.",
    question: "Is the bank open today?",
    options: ["Yes, it is open", "No, it is closed", "It is open at night", "It is never open"], correct_index: 1,
    explanation_en: "The text says the bank is closed today, so it is not open today.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "Omar drinks tea every morning. He likes it with sugar.",
    question: "What does Omar drink every morning?",
    options: ["Milk", "Juice", "Tea", "Water"], correct_index: 2,
    explanation_en: "The text states Omar drinks tea every morning.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "The pen is red. The book is blue.",
    question: "What colour is the book?",
    options: ["Red", "Green", "Blue", "Black"], correct_index: 2,
    explanation_en: "The text says the book is blue.",
  },
  {
    skill: "reading", cefr: "A1",
    content: "Maria has a small car. The car is white.",
    question: "What colour is Maria's car?",
    options: ["Black", "White", "Red", "Yellow"], correct_index: 1,
    explanation_en: "The text states Maria's car is white.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Sara works at a bank in the city. She starts work at nine o'clock and finishes at five o'clock, but on Fridays she goes home early.",
    question: "What time does Sara usually finish work?",
    options: ["At nine o'clock", "At five o'clock", "Early on Fridays", "At the weekend"], correct_index: 1,
    explanation_en: "The text states she finishes at five o'clock, with Friday given as the early exception.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Our office is on the third floor. There is a small kitchen next to the meeting room, and you can make tea or coffee there for free.",
    question: "Where can you make coffee in the office?",
    options: ["On the first floor", "In the meeting room", "In the small kitchen", "At the reception desk"], correct_index: 2,
    explanation_en: "The passage says the kitchen next to the meeting room is where you can make tea or coffee.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Ahmed sends a lot of emails every day because he works with many customers. He likes his job, but he says the phone rings too much.",
    question: "Why does Ahmed send many emails?",
    options: ["Because he works with many customers", "Because he does not like the phone", "Because he starts work early", "Because the office is busy"], correct_index: 0,
    explanation_en: "The text directly states he sends many emails because he works with many customers.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "The team meeting is on Monday morning at ten o'clock. Please bring your notes and a pen, because the manager wants to talk about the new project.",
    question: "What should people bring to the meeting?",
    options: ["A laptop and a phone", "Their notes and a pen", "Tea and coffee", "A new project plan"], correct_index: 1,
    explanation_en: "The passage asks people to bring their notes and a pen.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Maria takes the bus to work every day. The bus is cheap and fast, but sometimes it is late when the weather is bad.",
    question: "When is the bus sometimes late?",
    options: ["Every morning", "When the weather is bad", "On Mondays", "When it is cheap"], correct_index: 1,
    explanation_en: "The text says the bus is sometimes late when the weather is bad.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "The shop opens at eight in the morning and closes at ten at night. On Sundays it opens later, at eleven o'clock.",
    question: "What time does the shop open on Sundays?",
    options: ["At eight o'clock", "At ten o'clock", "At eleven o'clock", "At night"], correct_index: 2,
    explanation_en: "The passage states the shop opens later on Sundays, at eleven o'clock.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Omar wants to learn English because he needs it for his new job. He studies for one hour every evening after dinner.",
    question: "When does Omar study English?",
    options: ["Before breakfast", "Every evening after dinner", "At his new job", "On the weekend only"], correct_index: 1,
    explanation_en: "The text says he studies for one hour every evening after dinner.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Our company has a big car park behind the building. It is free for staff, but visitors must pay a small fee at the gate.",
    question: "Who must pay to use the car park?",
    options: ["The staff", "The visitors", "Everyone", "Nobody"], correct_index: 1,
    explanation_en: "The passage says the car park is free for staff but visitors must pay a small fee.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "Lina is a new worker in the accounts team. She is friendly and helpful, and she always answers questions quickly.",
    question: "What is Lina like?",
    options: ["Friendly and helpful", "Tired and busy", "Quiet and slow", "Serious and strict"], correct_index: 0,
    explanation_en: "The text describes Lina as friendly and helpful; the other options are not supported by the passage.",
  },
  {
    skill: "reading", cefr: "A2",
    content: "The report is due on Wednesday, so we must finish it soon. John will write the first part and Aisha will check the numbers.",
    question: "What will Aisha do?",
    options: ["Write the first part", "Check the numbers", "Send the report", "Read the notes"], correct_index: 1,
    explanation_en: "The passage states that Aisha will check the numbers.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "Our department switched to a new expense-tracking app last month. Although most staff found it easy to use, a few colleagues in the finance team said the reports took longer to prepare than before.",
    question: "What does the passage suggest about the new app?",
    options: ["Everyone in the company disliked it.", "It was generally easy to use, but not for everyone.", "It was only used by the finance team.", "It made all reports faster to prepare."], correct_index: 1,
    explanation_en: "The text says most staff found it easy while a few in finance found reports slower, so the app was generally easy but not for everyone.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "Fatima usually takes the train to the office, but when there is heavy rain she prefers to work from home. She says the crowded, delayed journey leaves her tired before the day has even started.",
    question: "What can we understand about Fatima from the passage?",
    options: ["She dislikes her job at the office.", "She avoids a difficult commute when the weather is bad.", "She is not allowed to travel by train in the rain.", "She works from home every day of the week."], correct_index: 1,
    explanation_en: "Fatima chooses to work from home in heavy rain because the journey becomes crowded and tiring, so she avoids a difficult commute in bad weather. The other options add facts the text does not support.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "The bank has introduced a small monthly fee for paper statements, but customers can avoid it completely by choosing electronic statements instead. Managers hope this change will reduce printing costs across all branches.",
    question: "Why did the bank introduce this change?",
    options: ["To increase the fees on all customer accounts.", "To encourage customers to move away from paper and cut printing costs.", "To close some of its branches to save money.", "To stop sending statements to customers altogether."], correct_index: 1,
    explanation_en: "The fee applies only to paper statements and can be avoided by going electronic, and managers want to reduce printing costs, so the aim is to move customers away from paper. The bank still sends statements, just electronically.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "Our team met the sales target this quarter, but only because two large clients placed unexpected orders in the final week. The manager warned that we cannot rely on such luck every time.",
    question: "What is the manager's main concern?",
    options: ["The team failed to reach its target.", "Success this quarter depended partly on luck.", "The two clients will not pay on time.", "The final week was too short for orders."], correct_index: 1,
    explanation_en: "The manager warns against relying on luck, implying the target was met partly by chance rather than steady performance.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "The training session was moved from Tuesday to Thursday so that more people could attend. Even so, several employees who work part-time will still miss it because they are not in the office on Thursdays.",
    question: "Why will some part-time employees still miss the session?",
    options: ["They do not want to attend the training.", "They are not in the office on Thursdays.", "The session was cancelled completely.", "They already attended it on Tuesday."], correct_index: 1,
    explanation_en: "The text explains that part-time staff will miss it because they do not work on Thursdays, the new day.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "When Omar started his new role, he found the software confusing and made several mistakes. After a few weeks of practice, however, he became one of the fastest workers in the team.",
    question: "What does the passage tell us about Omar?",
    options: ["He never learned to use the software.", "He improved a lot after some practice.", "He was the fastest worker from his first day.", "He left the team after making mistakes."], correct_index: 1,
    explanation_en: "Omar struggled at first but became one of the fastest after practising, showing clear improvement over time.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "The company offers staff a choice between a yearly bonus and extra holiday days. Younger employees tend to choose the bonus, while those with families often prefer more time off.",
    question: "What does the passage suggest about how staff make their choice?",
    options: ["Everyone chooses the yearly bonus.", "Their choice often depends on their personal situation.", "Only managers are allowed to choose extra holiday.", "Staff must take both the bonus and the holiday."], correct_index: 1,
    explanation_en: "The text contrasts younger employees choosing the bonus with those who have families preferring time off, suggesting the choice depends on personal circumstances.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "The new coffee machine on the third floor is popular, so there is often a long queue in the morning. To save time, some staff now bring their own drinks from home.",
    question: "Why do some staff bring drinks from home?",
    options: ["Because the coffee machine is broken.", "Because they do not like the free coffee.", "To avoid waiting in the morning queue.", "Because drinks from home are cheaper."], correct_index: 2,
    explanation_en: "Staff bring their own drinks to save time and avoid the long morning queue at the machine.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "Although the report was due on Friday, the team asked for two more days because some of the data arrived late. The client agreed, but asked to see a short summary before the weekend.",
    question: "What did the client request?",
    options: ["The full report by Friday.", "A short summary before the weekend.", "A meeting with the whole team.", "A refund for the delay."], correct_index: 1,
    explanation_en: "The client agreed to the extension but asked to see a short summary before the weekend.",
  },
  {
    skill: "reading", cefr: "B1",
    content: "Our office recycles paper and plastic, but many people still throw everything into one bin out of habit. The building manager plans to add clearer signs to help staff sort their waste correctly.",
    question: "Why does the building manager want to add clearer signs?",
    options: ["To help staff sort their waste correctly.", "To stop staff from using the bins.", "To reduce the number of bins in the office.", "To explain how the recycling is collected."], correct_index: 0,
    explanation_en: "The signs are meant to help staff, who often mix waste out of habit, sort it correctly.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The finance committee approved the new expansion budget, though several members privately doubted that the projected returns would materialise within the promised timeframe. Their concerns were noted in the minutes but did not block the vote.",
    question: "What can be inferred about the committee members?",
    options: ["They unanimously believed the expansion would succeed quickly", "Some had reservations yet still allowed the budget to pass", "They rejected the budget because of the doubts raised", "They postponed the vote until the returns were confirmed"], correct_index: 1,
    explanation_en: "The phrases 'privately doubted' and 'did not block the vote' show members had reservations but still let the budget through.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "Rather than cutting staff outright, the bank chose to redeploy employees whose roles had been automated into customer-facing positions. Management framed this as a retention strategy, but analysts suspected it was mainly a way to avoid the reputational cost of layoffs.",
    question: "According to the text, why do analysts think the bank redeployed staff?",
    options: ["To genuinely reward loyal long-serving employees", "To reduce the negative publicity that layoffs would create", "Because customer-facing roles paid significantly more", "Because automation had failed to work as intended"], correct_index: 1,
    explanation_en: "The analysts 'suspected it was mainly a way to avoid the reputational cost of layoffs', pointing to publicity as the real motive.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The quarterly report highlighted record revenue but buried, in a footnote, the fact that a one-off legal settlement accounted for nearly half of that growth. Without it, the underlying business had barely improved on the previous year.",
    question: "What is the main point the passage makes about the company's growth?",
    options: ["The record revenue reflected strong underlying performance", "Much of the reported growth came from an unusual, non-recurring event", "The legal settlement had no effect on the reported figures", "Revenue had fallen compared with the previous year"], correct_index: 1,
    explanation_en: "The passage stresses that a 'one-off legal settlement' drove nearly half the growth, so the underlying business barely improved.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "New employees are encouraged to question established procedures during their first months, since fresh perspectives often reveal inefficiencies that longer-serving staff have stopped noticing. The company treats this early scepticism as an asset rather than a nuisance.",
    question: "Why does the company value new employees questioning procedures?",
    options: ["Because new staff are usually better qualified than existing staff", "Because newcomers can spot problems that experienced staff overlook", "Because it reduces the amount of training that is required", "Because established procedures are known to be ineffective"], correct_index: 1,
    explanation_en: "The text says fresh perspectives 'reveal inefficiencies that longer-serving staff have stopped noticing', so newcomers spot overlooked problems.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The consultancy's proposal was technically sound, but the client ultimately went with a rival whose presentation, while less rigorous, spoke directly to the board's anxieties about market volatility. Substance, it seemed, had lost out to reassurance.",
    question: "Why did the client choose the rival consultancy?",
    options: ["Its proposal contained more accurate technical analysis", "It addressed the board's worries more directly, despite being less thorough", "It offered a considerably lower price for the same work", "It had a longer track record in the client's industry"], correct_index: 1,
    explanation_en: "The rival 'spoke directly to the board's anxieties' and won although 'less rigorous', so reassurance beat substance.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "When the supplier raised its prices, our procurement team did not simply accept the increase; instead they renegotiated the delivery schedule so that larger, less frequent shipments offset most of the added cost. The final invoice rose only marginally.",
    question: "How did the procurement team respond to the price increase?",
    options: ["They refused to work with the supplier any longer", "They accepted the higher prices without any changes", "They adjusted the delivery arrangements to limit the extra cost", "They found an alternative supplier with cheaper prices"], correct_index: 2,
    explanation_en: "They 'renegotiated the delivery schedule' with larger, less frequent shipments to offset the cost, so the invoice rose only marginally.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The training programme was popular and well attended, yet a follow-up review found little change in how participants actually did their jobs six months later. Enthusiasm in the room, the reviewers concluded, was a poor predictor of lasting behaviour.",
    question: "What did the follow-up review conclude about the training?",
    options: ["The programme successfully changed long-term work habits", "High attendance guaranteed the programme's usefulness", "Participants' enthusiasm did not translate into lasting change", "The training should be made compulsory for all staff"], correct_index: 2,
    explanation_en: "The review found 'little change' after six months and that enthusiasm 'was a poor predictor of lasting behaviour'.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The startup's founders insisted that turning down the acquisition offer was about protecting their vision, not the money. Observers noted, however, that a competing bid was rumoured to be circulating, which may have made patience the more profitable choice.",
    question: "What do the observers suggest about the founders' decision?",
    options: ["It was driven purely by loyalty to their original vision", "It may also have been financially motivated by a possible higher bid", "It showed the founders did not understand the offer's value", "It was made against the advice of their investors"], correct_index: 1,
    explanation_en: "Observers point to a rumoured competing bid that 'may have made patience the more profitable choice', hinting at a financial motive.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "Although the survey reported high overall satisfaction, the responses were collected only from clients who had renewed their contracts. Those who had already left, and might have explained why, were never asked.",
    question: "Why should the survey's positive result be treated with caution?",
    options: ["The sample excluded dissatisfied clients who had left", "Too few clients responded for the result to be meaningful", "The questions were written in a confusing way", "Clients were paid to give positive answers"], correct_index: 0,
    explanation_en: "Only renewing clients were surveyed, so departed, likely dissatisfied clients were excluded, biasing the result.",
  },
  {
    skill: "reading", cefr: "B2",
    content: "The manager praised the team's initiative in public but, in the same breath, reminded everyone that all future changes would first need her written approval. The message was welcomed warmly at first, then re-read more warily.",
    question: "What does the passage imply about the manager's message?",
    options: ["It was straightforwardly encouraging to the team", "It contained a subtle restriction that undercut the praise", "It was an outright criticism of the team's recent work", "It gave the team complete freedom to make changes"], correct_index: 1,
    explanation_en: "Praising initiative while requiring her approval for all changes is a subtle restriction, which is why the team re-read it 'more warily'.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The board's endorsement of the merger was, at best, lukewarm; while no director voted against it, the terse minutes recorded a conspicuous absence of the customary language praising strategic vision.",
    question: "What does the passage imply about the board's attitude toward the merger?",
    options: ["The directors were enthusiastic but constrained by procedure", "The directors approved it without genuine conviction", "The directors were legally prevented from opposing it", "The directors unanimously rejected the strategic rationale"], correct_index: 1,
    explanation_en: "The absence of praise and the 'lukewarm' framing signal formal approval unaccompanied by real enthusiasm, which the reader must infer.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The consultant's report stopped short of recommending redundancies outright, but its repeated emphasis on 'right-sizing the cost base' left little to the imagination of anyone who had sat through similar exercises before.",
    question: "What is the report actually signalling?",
    options: ["That job cuts are the likely outcome despite the softened wording", "That the company should hire more staff to control costs", "That costs are already at an appropriate level", "That the consultant refused to give any recommendation"], correct_index: 0,
    explanation_en: "The euphemism 'right-sizing the cost base' and the knowing reference to past exercises imply redundancies without stating them directly.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "Analysts had expected the central bank to hold rates, so its decision to cut by a quarter point was less a routine adjustment than a tacit admission that the economy was weaker than official forecasts had let on.",
    question: "How does the writer interpret the rate cut?",
    options: ["As a scheduled move consistent with prior guidance", "As evidence the economy was performing above expectations", "As an implicit acknowledgement of unexpected economic weakness", "As a deliberate attempt to mislead analysts"], correct_index: 2,
    explanation_en: "'Tacit admission' and 'weaker than forecasts had let on' frame the cut as an unspoken concession of hidden weakness.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The new compliance officer was scrupulously polite to everyone, yet staff quickly learned that a request phrased as a suggestion from her desk was one they ignored at their peril.",
    question: "What can be inferred about the compliance officer's 'suggestions'?",
    options: ["They were optional and rarely enforced", "They were resented because she was rude", "They were effectively binding instructions despite their soft phrasing", "They were ignored without any consequence"], correct_index: 2,
    explanation_en: "'Ignored at their peril' shows the polite suggestions carried the weight of orders, an implicit meaning the reader must decode.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "For all the fanfare surrounding the product launch, the quarterly figures told a more sober story: initial sales had been brisk, but the steep drop in repeat purchases pointed to a novelty that had worn thin.",
    question: "What underlying problem do the figures reveal?",
    options: ["Customers bought once but were not returning", "The product failed to attract any early buyers", "The launch received too little marketing attention", "Repeat purchases were steadily increasing"], correct_index: 0,
    explanation_en: "The contrast between brisk first sales and a drop in repeat purchases implies customers tried the product but did not stay loyal.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The minister praised the region's 'resilient and adaptive labour market', a formulation that seasoned observers took as a diplomatic gloss over persistently high youth unemployment.",
    question: "Why do observers read the minister's phrase sceptically?",
    options: ["Because they believe the labour market is genuinely thriving", "Because the minister was quoting official statistics accurately", "Because youth unemployment had recently disappeared", "Because it papers over a real and ongoing employment problem"], correct_index: 3,
    explanation_en: "'Diplomatic gloss over persistently high youth unemployment' signals the upbeat phrase masks an unresolved problem.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "Whereas her predecessor had chased headline growth at almost any cost, the incoming chief executive spoke instead of 'disciplined expansion', signalling to investors that the era of acquisitions financed by mounting debt was drawing to a close.",
    question: "What change in strategy does the new chief executive imply?",
    options: ["A return to aggressive, debt-fuelled growth", "An abandonment of any growth ambitions", "A shift toward more cautious, financially prudent growth", "A continuation of the predecessor's approach unchanged"], correct_index: 2,
    explanation_en: "'Disciplined expansion' contrasted with debt-financed acquisitions implies a deliberately more prudent growth strategy.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The audit uncovered no outright fraud, but the tangle of related-party transactions and the reluctance of certain managers to produce documentation suggested a culture in which awkward questions were not encouraged.",
    question: "What does the passage suggest about the organisation's culture?",
    options: ["It discouraged scrutiny even in the absence of proven fraud", "It was fully transparent and cooperative with auditors", "It had committed clear and deliberate fraud", "It welcomed difficult questions from all staff"], correct_index: 0,
    explanation_en: "Despite no proven fraud, the opacity and reluctance imply a culture hostile to scrutiny, which the reader must infer.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The startup's founders were quick to attribute their setback to 'challenging market conditions', though competitors operating in the very same market had, that quarter, posted their strongest results in years.",
    question: "What does the juxtaposition in the passage imply?",
    options: ["The market really was uniformly difficult for everyone", "The competitors had also failed that quarter", "The setback was entirely beyond anyone's control", "The founders' explanation deflects from problems of their own making"], correct_index: 3,
    explanation_en: "Rivals thriving in the same market undercuts the 'market conditions' excuse, implying the founders' own failings were at fault.",
  },
  {
    skill: "reading", cefr: "C1",
    content: "The training programme was billed as voluntary, but with attendance quietly noted and promotions increasingly going to those who had completed it, few employees felt they could realistically decline.",
    question: "What does the passage reveal about the 'voluntary' programme?",
    options: ["It was genuinely optional with no bearing on careers", "It was formally mandatory for all employees", "It was voluntary in name but effectively compulsory in practice", "It had no connection to promotion decisions"], correct_index: 2,
    explanation_en: "Tracked attendance and its link to promotions make the programme coercive despite its 'voluntary' label, an implied contradiction.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "The board's endorsement of the restructuring was, one might charitably say, less than wholehearted; had the alternative not carried even graver reputational hazards, one suspects the proposal would have been quietly interred rather than ratified.",
    question: "What is implied about the board's decision?",
    options: ["It approved the restructuring chiefly because rejecting it seemed worse, not because it favoured the plan", "It approved the restructuring enthusiastically after weighing the reputational benefits", "It rejected the restructuring on reputational grounds", "It postponed the decision indefinitely to avoid reputational damage"], correct_index: 0,
    explanation_en: "The phrasing signals reluctant approval driven by the alternative being even more damaging, not genuine support for the proposal.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "To call the quarter's returns 'robust' would be to mistake the flattery of a favourable base effect for underlying vigour; strip out the prior period's collapse and the celebrated rebound dwindles to something closer to stagnation.",
    question: "What is the writer's main point about the quarter's returns?",
    options: ["The returns were genuinely strong and reflect real underlying growth", "The prior period's collapse was caused by the same factors as this quarter", "The apparent strength is largely an artefact of comparison with a very weak prior period", "The returns should be celebrated despite the base effect"], correct_index: 2,
    explanation_en: "The writer argues the impressive figure is inflated by comparison against a collapsed baseline and that real growth is near-flat.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "The consultant's report was a masterpiece of strategic ambiguity: every recommendation was hedged so exquisitely that, whatever the client ultimately chose to do, the firm could later claim to have advised precisely that course.",
    question: "What is the writer suggesting about the report?",
    options: ["Its recommendations were precise and actionable", "It offered a single bold recommendation the client ignored", "Its ambiguity stemmed from the consultant's incompetence", "It was deliberately vague so the firm could retrospectively appear correct regardless of outcome"], correct_index: 3,
    explanation_en: "The ironic praise indicates calculated vagueness engineered to preserve the firm's credibility whatever the client decides.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "For all the fanfare surrounding the merger, the two cultures proved as compatible as oil and water; the integration committee's cheerful bulletins grew, month by month, ever more strenuously upbeat, in inverse proportion to any evidence on the ground.",
    question: "What does the passage imply about the integration?",
    options: ["The bulletins became more relentlessly positive precisely because the actual integration was failing", "The cultures blended smoothly and the bulletins accurately reflected progress", "The integration committee was disbanded after early success", "The merger fanfare was justified by strong cultural alignment"], correct_index: 0,
    explanation_en: "The oil-and-water image plus the inverse-proportion remark signals the upbeat messaging masked a lack of real progress.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "The regulator's newfound zeal for transparency, arriving as it did on the very heels of the scandal, struck seasoned observers less as a conversion of principle than as an exercise in belated self-preservation.",
    question: "How did seasoned observers interpret the regulator's push for transparency?",
    options: ["As a sincere and long-held commitment to openness", "As a reactive move to protect itself after the scandal rather than a genuine change of principle", "As an overreaction that damaged the regulator's standing", "As a policy unrelated to the recent scandal"], correct_index: 1,
    explanation_en: "The contrast between 'conversion of principle' and 'belated self-preservation' shows observers read the move as self-protective damage control.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "Her memo conceded the forecasting error with a candour so conspicuous, so lavishly detailed, that the reader was left wondering whether the confession's real function was less to accept blame than to parade a scrupulousness that pre-empted any harsher judgement.",
    question: "What does the writer suggest about the memo's candour?",
    options: ["It was a straightforward and complete acceptance of responsibility", "It concealed the forecasting error from readers", "Its very thoroughness may have been a tactic to appear scrupulous and deflect harsher criticism", "It was too vague to constitute a real confession"], correct_index: 2,
    explanation_en: "The writer hints the ostentatious honesty may have been strategic self-presentation designed to forestall sterner blame.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "The initiative was not so much abandoned as allowed to expire of neglect; no one moved to kill it outright, yet each successive budget review found some more pressing claimant for the funds it had once been promised.",
    question: "What happened to the initiative?",
    options: ["It quietly died from persistent underfunding rather than any explicit decision to end it", "It was formally cancelled in a single decisive budget review", "It was fully funded but failed for other reasons", "It was merged into a more pressing initiative"], correct_index: 0,
    explanation_en: "The passage describes death by attrition, with funds repeatedly diverted, rather than an outright cancellation.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "The analyst's caveats, buried in a footnote no client would trouble to read, were technically sufficient to absolve the firm of any charge of having oversold the instrument, while doing nothing whatever to dispel the impression the headline had so carefully cultivated.",
    question: "What is implied about the analyst's caveats?",
    options: ["They were prominent enough to correct the misleading headline", "They persuaded clients not to buy the instrument", "They contradicted the firm's own headline claims openly", "They satisfied a formal disclosure duty while leaving the misleading impression intact"], correct_index: 3,
    explanation_en: "The footnote met the letter of disclosure yet was placed so as not to undo the headline's cultivated impression.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "That the pilot scheme 'exceeded expectations' tells us rather less than its authors intend, for expectations had been set, with a prudence bordering on the cynical, low enough that almost any outcome short of catastrophe would have cleared the bar.",
    question: "Why is the writer sceptical of the claim that the scheme exceeded expectations?",
    options: ["Because the scheme actually performed catastrophically", "Because the expectations were deliberately set so low that surpassing them means little", "Because the authors misreported the scheme's results", "Because the pilot scheme was never actually run"], correct_index: 1,
    explanation_en: "The writer notes the benchmark was cynically low, so 'exceeding' it is an unimpressive and near-meaningless achievement.",
  },
  {
    skill: "reading", cefr: "C2",
    content: "He was promoted, as the euphemism has it, to a role of 'strategic oversight' - a corner office, an impressive title, and a portfolio of responsibilities from which every lever of actual consequence had been quietly detached.",
    question: "What does the passage suggest about the promotion?",
    options: ["It gave him greater real authority over strategy", "It was a demotion openly acknowledged as such", "It was a nominal elevation that stripped him of genuine power while preserving appearances", "It increased his workload without changing his influence"], correct_index: 2,
    explanation_en: "The ironic 'euphemism' and 'detached levers' reveal a face-saving sidelining dressed up as a promotion.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "Hello. My name is Sara. I work in a bank.",
    question: "Where does Sara work?",
    options: ["In a bank", "In a school", "In a shop", "In a hospital"], correct_index: 0,
    explanation_en: "Sara says directly that she works in a bank.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "The meeting is at ten o'clock. Please come to room five.",
    question: "What time is the meeting?",
    options: ["At nine o'clock", "At ten o'clock", "At eleven o'clock", "At five o'clock"], correct_index: 1,
    explanation_en: "The speaker states the meeting is at ten o'clock.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "I have two brothers and one sister.",
    question: "How many brothers does the speaker have?",
    options: ["One", "Two", "Three", "Four"], correct_index: 1,
    explanation_en: "The speaker says he has two brothers.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "My office is on the third floor. The lift is near the door.",
    question: "Which floor is the office on?",
    options: ["The first floor", "The second floor", "The third floor", "The fourth floor"], correct_index: 2,
    explanation_en: "The speaker says the office is on the third floor.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "I drink coffee every morning. I like it with milk.",
    question: "What does the speaker drink every morning?",
    options: ["Tea", "Water", "Coffee", "Juice"], correct_index: 2,
    explanation_en: "The speaker says he drinks coffee every morning.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "Today is Monday. We are open until six.",
    question: "What day is it today?",
    options: ["Sunday", "Monday", "Friday", "Saturday"], correct_index: 1,
    explanation_en: "The speaker says today is Monday.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "My new pen is blue. It is on the desk.",
    question: "What colour is the pen?",
    options: ["Red", "Green", "Blue", "Black"], correct_index: 2,
    explanation_en: "The speaker says the pen is blue.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "The shop opens at nine in the morning.",
    question: "What time does the shop open?",
    options: ["At eight", "At nine", "At ten", "At seven"], correct_index: 1,
    explanation_en: "The speaker says the shop opens at nine.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "I go to work by bus. The bus stop is near my home.",
    question: "How does the speaker go to work?",
    options: ["By car", "By bus", "By train", "On foot"], correct_index: 1,
    explanation_en: "The speaker says he goes to work by bus.",
  },
  {
    skill: "listening", cefr: "A1",
    content: "My manager's name is Mr Khan. He sits next to me.",
    question: "What is the manager's name?",
    options: ["Mr Ali", "Mr Khan", "Mr Sami", "Mr Omar"], correct_index: 1,
    explanation_en: "The speaker says the manager's name is Mr Khan.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "The meeting starts at nine o'clock, but please come at half past eight because we need to set up the room first.",
    question: "What time should people arrive?",
    options: ["At nine o'clock", "At half past eight", "At half past nine", "At eight o'clock"], correct_index: 1,
    explanation_en: "The speaker asks people to come at half past eight, before the nine o'clock start, to set up the room.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "I usually take the bus to the office, but today it was late, so I took a taxi instead.",
    question: "How did the speaker get to the office today?",
    options: ["By bus", "By taxi", "By car", "On foot"], correct_index: 1,
    explanation_en: "The speaker normally takes the bus, but today the bus was late so they took a taxi.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "Our new manager is from Dubai, and she speaks both English and Arabic very well.",
    question: "What languages does the new manager speak?",
    options: ["Only English", "Only Arabic", "English and Arabic", "English and French"], correct_index: 2,
    explanation_en: "The speaker states the manager speaks both English and Arabic well.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "The printer on the second floor is not working, so please use the one near the kitchen today.",
    question: "Which printer should people use today?",
    options: ["The one on the second floor", "The one near the kitchen", "The one in the manager's office", "No printer is available"], correct_index: 1,
    explanation_en: "Because the second-floor printer is broken, the speaker asks people to use the one near the kitchen.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "I can't come to lunch today because I have a lot of emails to answer before three o'clock.",
    question: "Why can't the speaker come to lunch?",
    options: ["They are not hungry", "They have many emails to answer", "They are going home early", "They have a meeting at lunch"], correct_index: 1,
    explanation_en: "The speaker says they have a lot of emails to answer before three o'clock, so they can't come to lunch.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "The training on Monday is now on Wednesday, but it is still in the same room on the third floor.",
    question: "What has changed about the training?",
    options: ["The room", "The day", "The teacher", "The topic"], correct_index: 1,
    explanation_en: "The training moved from Monday to Wednesday, but the room stayed the same.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "Please send me the report by email today, and bring a printed copy to the meeting tomorrow.",
    question: "What should the person bring to the meeting tomorrow?",
    options: ["A laptop", "A printed copy of the report", "An email address", "A new report"], correct_index: 1,
    explanation_en: "The speaker asks for the report by email today and a printed copy at tomorrow's meeting.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "The coffee machine is free for everyone, but the small fridge is only for the sales team.",
    question: "Who can use the small fridge?",
    options: ["Everyone", "Only the sales team", "Only managers", "No one"], correct_index: 1,
    explanation_en: "The coffee machine is for everyone, but the fridge is only for the sales team.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "I finished the first part of the project, but I need one more day to finish the second part.",
    question: "What does the speaker still need to do?",
    options: ["Start the project", "Finish the first part", "Finish the second part", "Check the whole project"], correct_index: 2,
    explanation_en: "The speaker finished the first part and needs one more day for the second part.",
  },
  {
    skill: "listening", cefr: "A2",
    content: "Our office is closed on Friday because of a public holiday, so we will open again on Saturday morning.",
    question: "When will the office open again?",
    options: ["Friday morning", "Saturday morning", "Sunday morning", "Thursday morning"], correct_index: 1,
    explanation_en: "The office is closed Friday for a holiday and opens again Saturday morning.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "The training session that was planned for Thursday has been moved to next Monday, because the meeting room is being repainted this week.",
    question: "Why has the training session been moved?",
    options: ["The trainer is not available on Thursday", "The meeting room is being repainted", "Not enough people signed up for it", "The session was cancelled completely"], correct_index: 1,
    explanation_en: "The speaker states the session was moved because the meeting room is being repainted this week.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "I've looked at both suppliers, and although the first one is a little cheaper, I think we should go with the second, because they deliver much faster.",
    question: "Which supplier does the speaker prefer, and why?",
    options: ["The first one, because it is cheaper", "The second one, because it delivers faster", "The first one, because it delivers faster", "The second one, because it is cheaper"], correct_index: 1,
    explanation_en: "The speaker prefers the second supplier despite its higher price, because it delivers much faster.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "Our new online banking app was supposed to launch in March, but the team found a few security problems, so we've decided to wait until they are fixed.",
    question: "What is the main point the speaker is making?",
    options: ["The app launched successfully in March", "The launch is delayed until the security problems are fixed", "The app has no security problems", "The team has decided to cancel the app"], correct_index: 1,
    explanation_en: "The main idea is that the launch is delayed until the security problems the team found are fixed.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "When you fill in the expense form, remember to attach your receipts; otherwise the finance department will send it back to you.",
    question: "What will happen if you do not attach your receipts?",
    options: ["Finance will approve the form anyway", "The finance department will send the form back", "You will be paid twice", "The form will be deleted from the system"], correct_index: 1,
    explanation_en: "The speaker warns that without receipts the finance department will send the form back.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "Sales were quite slow in the first half of the year, but they picked up over the summer, so overall we're happy with how the year has gone.",
    question: "How does the speaker feel about the year overall?",
    options: ["Disappointed, because sales stayed slow all year", "Satisfied, because sales improved later on", "Worried about the year ahead", "Surprised that sales fell in the summer"], correct_index: 1,
    explanation_en: "Although sales started slowly, they improved over the summer, and the speaker says they are happy overall.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "If you have any questions about your new contract, you should speak to Sara in Human Resources rather than emailing the manager directly.",
    question: "Who should you contact about the contract?",
    options: ["The manager, by email", "Sara in Human Resources", "The finance department", "Your closest colleague"], correct_index: 1,
    explanation_en: "The speaker advises contacting Sara in Human Resources instead of emailing the manager directly.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "The client asked us to prepare the report in both English and Arabic, but since our translator is on holiday, the Arabic version will be ready a week later.",
    question: "Why will the Arabic version be late?",
    options: ["The client changed the language it wanted", "The translator is on holiday", "The report turned out to be too long", "The English version was rejected"], correct_index: 1,
    explanation_en: "The Arabic version will be a week late because the translator is on holiday.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "I'd recommend taking the train to the conference instead of driving, because parking near the venue is very expensive and often full.",
    question: "Why does the speaker recommend taking the train?",
    options: ["The train is faster than driving", "Parking is expensive and often full", "The venue has no car park at all", "Driving into the city is not allowed"], correct_index: 1,
    explanation_en: "The speaker recommends the train because parking near the venue is expensive and often full.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "We got a lot of good feedback about the workshop, but several people said the lunch break was too short, so we'll make it longer next time.",
    question: "What change will be made next time?",
    options: ["The whole workshop will be shorter", "The lunch break will be longer", "Lunch will no longer be provided", "The feedback forms will be removed"], correct_index: 1,
    explanation_en: "Because people said the lunch break was too short, the speaker says they will make it longer next time.",
  },
  {
    skill: "listening", cefr: "B1",
    content: "Please make sure you save your work to the shared drive before you leave today, as the IT team will be updating the computers overnight.",
    question: "Why should staff save their work to the shared drive?",
    options: ["Because the office is closing early today", "Because IT will update the computers overnight", "Because the shared drive is being deleted", "Because everyone is moving to new desks"], correct_index: 1,
    explanation_en: "Staff are asked to save to the shared drive because the IT team will update the computers overnight.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "The finance director mentioned that although the new expense system was rolled out on time, several departments are still emailing their receipts the old way, which is slowing down the whole approval process.",
    question: "What problem does the speaker point out?",
    options: ["The new expense system was launched later than planned.", "Some departments have not adopted the new system, causing delays.", "The approval process was removed to save time.", "Receipts can no longer be submitted by email."], correct_index: 1,
    explanation_en: "The speaker says the system launched on time but some departments still use the old email method, which slows approvals - so the issue is incomplete adoption.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "Honestly, the presentation itself was polished, but the figures she quoted didn't quite match the ones in last month's report, so I'd want to double-check them before we share anything with the client.",
    question: "What is the speaker's main concern?",
    options: ["The presentation looked unprofessional.", "The client has already seen the report.", "The numbers may be inaccurate and need verifying.", "Last month's report was never finished."], correct_index: 2,
    explanation_en: "The speaker praises the delivery but flags that the figures conflict with the earlier report and should be checked, so the concern is accuracy.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "We were expecting the supplier to raise their prices this quarter, but instead they offered us a small discount, presumably because a competitor has just entered the market.",
    question: "Why does the speaker think the supplier offered a discount?",
    options: ["Because the supplier wanted to increase prices gradually.", "Because a new competitor has appeared in the market.", "Because the company ordered a larger quantity than usual.", "Because prices always fall at the end of the quarter."], correct_index: 1,
    explanation_en: "The speaker attributes the unexpected discount to a competitor recently entering the market ('presumably because').",
  },
  {
    skill: "listening", cefr: "B2",
    content: "The training went well overall, though I got the impression that the newer staff found the pace a bit fast, especially during the section on financial modelling.",
    question: "What does the speaker suggest about the training?",
    options: ["The whole session was too slow for everyone.", "The financial modelling section was cancelled.", "Experienced staff complained about the content.", "Newer staff may have struggled to keep up in parts."], correct_index: 3,
    explanation_en: "The speaker infers that newer staff found the pace fast, particularly during financial modelling - implying they had trouble keeping up.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "I know we'd agreed to meet in person on Thursday, but given how much everyone's travelling this week, it might make more sense to move it online and keep it short.",
    question: "What is the speaker proposing?",
    options: ["Cancelling Thursday's meeting entirely.", "Holding the meeting online instead of in person.", "Extending the meeting to allow for travel.", "Rescheduling the meeting to next week."], correct_index: 1,
    explanation_en: "Because of heavy travel, the speaker suggests switching the in-person meeting to a short online one, not cancelling or postponing it.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "The report claims our costs have fallen, but that's mainly because we stopped counting temporary contractors, not because we're actually spending any less.",
    question: "What point is the speaker making about the reported cost fall?",
    options: ["The apparent drop is due to a change in what is counted.", "Costs have genuinely dropped across the business.", "Temporary contractors are now more expensive.", "The report failed to include recent spending."], correct_index: 0,
    explanation_en: "The speaker argues the lower costs are an accounting effect - excluding contractors - rather than real savings.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "Our customers keep telling us they love the product, yet the renewal numbers tell a different story, so I think the real issue is how complicated our pricing has become.",
    question: "What does the speaker believe is the underlying problem?",
    options: ["Customers dislike the product itself.", "The pricing structure has become too complex.", "Renewal numbers are being recorded incorrectly.", "The company has too few customers."], correct_index: 1,
    explanation_en: "Despite positive feedback, weak renewals lead the speaker to conclude that complicated pricing is the real issue.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "We could hire two more analysts now, but unless we also invest in better software, we'll just end up with more people doing the same slow manual work.",
    question: "What is the speaker's main argument?",
    options: ["Hiring analysts alone won't fix the efficiency problem.", "The company should avoid hiring any new analysts.", "The current software is already good enough.", "Manual work should be given to the new analysts."], correct_index: 0,
    explanation_en: "The speaker argues that adding staff without better software would only multiply the same slow manual work, so hiring alone is insufficient.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "To be fair, the delay wasn't really the team's fault; the client kept changing the requirements right up until the deadline, which made it almost impossible to finish on time.",
    question: "What does the speaker say caused the delay?",
    options: ["The team worked too slowly.", "The deadline was set too early.", "The requirements were never explained.", "The client repeatedly changed the requirements."], correct_index: 3,
    explanation_en: "The speaker defends the team and blames the delay on the client's constant last-minute changes to requirements.",
  },
  {
    skill: "listening", cefr: "B2",
    content: "Sales in the region are up, which sounds encouraging, but most of that growth came from a single large order, so I wouldn't read too much into it just yet.",
    question: "Why does the speaker urge caution about the sales growth?",
    options: ["The growth figures were reported incorrectly.", "The growth depends heavily on one big order.", "Sales in the region have actually declined.", "The large order has not yet been confirmed."], correct_index: 1,
    explanation_en: "The speaker warns against over-interpreting the rise because it rests on a single large order rather than broad-based growth.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "Look, I'm not saying the acquisition was a mistake as such - the timing just meant we absorbed their liabilities right as the market turned, which is a rather different conversation.",
    question: "What is the speaker's attitude toward the acquisition?",
    options: ["They regret the decision and consider it a clear error.", "They defend the decision itself but question when it happened.", "They believe the acquisition improved the company's finances.", "They think the market turn had no effect on the outcome."], correct_index: 1,
    explanation_en: "The phrase 'not a mistake as such' plus 'the timing just meant' signals the speaker separates the sound decision from its poorly-timed execution.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "To be fair to the vendor, they did flag the integration risks early on; it's just that nobody on our side was in much of a hurry to read the fine print.",
    question: "Where does the speaker imply the fault primarily lies?",
    options: ["With their own team for not attending to the warnings", "With the vendor for concealing the integration risks", "With the fine print being deliberately misleading", "With the tight deadline imposed by the vendor"], correct_index: 0,
    explanation_en: "Crediting the vendor for flagging risks while noting 'nobody on our side' engaged with the details shifts the blame internally rather than onto the vendor.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "The quarterly figures look healthy enough on paper, but strip out the one-off asset sale and the underlying trend is a good deal less reassuring.",
    question: "What does the speaker suggest about the company's performance?",
    options: ["The core business is performing better than the figures show.", "The asset sale was an unwise decision.", "The headline figures overstate the true ongoing health of the business.", "The quarterly figures contain a reporting error."], correct_index: 2,
    explanation_en: "'Healthy on paper' contrasted with a 'less reassuring' underlying trend once the one-off sale is removed implies the surface numbers flatter the real picture.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "I'd hold off congratulating the team just yet - hitting the target this once tells us far less than whether they can do it again when conditions aren't quite so favourable.",
    question: "Why is the speaker cautious about praising the team?",
    options: ["The team did not actually meet the target.", "A single success under easy conditions doesn't prove reliability.", "The conditions are expected to remain favourable.", "The target itself was set too low to be meaningful."], correct_index: 1,
    explanation_en: "Weighing 'this once' against doing it again when 'conditions aren't so favourable' implies one win in good circumstances isn't yet evidence of consistent capability.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "The new compliance regime is being sold to us as a burden, but honestly, for a firm our size it's more of an invitation to finally tidy up processes we've been meaning to fix for years.",
    question: "How does the speaker view the new compliance regime?",
    options: ["As an unnecessary obstacle to the firm's operations", "As a rule that applies unfairly to smaller firms", "As something the firm has already fully addressed", "As an opportunity disguised as a constraint"], correct_index: 3,
    explanation_en: "Rejecting the 'burden' framing in favour of 'an invitation to tidy up' shows the speaker reads the regulation as a welcome prompt rather than a hindrance.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "She presented three forecasting models, and while she stopped short of endorsing any one of them outright, it wasn't hard to tell which she'd stake her own reputation on.",
    question: "What can be inferred about the presenter?",
    options: ["She subtly conveyed a preference despite not stating it directly.", "She refused to express any preference among the models.", "She openly recommended one model over the others.", "She considered all three models equally unreliable."], correct_index: 0,
    explanation_en: "'Stopped short of endorsing' yet 'wasn't hard to tell which she'd stake her reputation on' means a clear preference came through implicitly.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "Rolling out the platform region by region would have been the prudent call; instead we went live everywhere at once, and I think you can guess how the support desk felt about that.",
    question: "What does the speaker imply about the rollout?",
    options: ["The all-at-once rollout caused problems for the support desk.", "The region-by-region approach was ultimately chosen.", "The support desk welcomed the simultaneous launch.", "The platform was never actually rolled out."], correct_index: 0,
    explanation_en: "Calling the phased approach 'prudent' before noting they did the opposite, plus the ironic 'you can guess how the support desk felt', implies the mass launch overwhelmed support.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "The consultant's report is thorough, I'll grant her that, but it reads rather like a document written to be defensible rather than to actually recommend a course of action.",
    question: "What is the speaker's main criticism of the report?",
    options: ["It is too short to be useful.", "It contains factual inaccuracies throughout.", "It avoids commitment in order to protect its author.", "It recommends an overly risky course of action."], correct_index: 2,
    explanation_en: "'Written to be defensible rather than to recommend' implies the report is hedged to shield the author instead of offering a decisive recommendation.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "Everyone keeps pointing to the currency swings to explain the shortfall, and there's something in that, but it does conveniently let us off the hook for the margins we were already losing before any of that started.",
    question: "What point is the speaker making about the shortfall?",
    options: ["Currency swings are entirely to blame for the shortfall.", "The margins had been improving before the currency swings.", "The shortfall was smaller than people are claiming.", "Blaming the currency obscures pre-existing internal problems."], correct_index: 3,
    explanation_en: "Conceding 'something in that' while noting it 'conveniently lets us off the hook' for margins already slipping implies the currency story masks earlier internal failings.",
  },
  {
    skill: "listening", cefr: "C1",
    content: "He's been with us twenty years and knows the systems inside out, which is precisely why his reluctance to touch the new tools ought to worry us far more than any hesitation from the graduates would.",
    question: "Why does the veteran employee's reluctance concern the speaker?",
    options: ["Because he lacks the experience to judge the new tools", "Because resistance from someone so knowledgeable is especially telling", "Because the graduates are equally reluctant to adapt", "Because he is likely to leave the company soon"], correct_index: 1,
    explanation_en: "'Precisely why' links his deep expertise to why his reluctance 'ought to worry us more' - a well-informed sceptic's resistance carries more weight than a newcomer's.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "I'd stop short of calling the guidance disingenuous, but the way the CFO buried the covenant waiver in a footnote does rather test the boundary between technical compliance and candour.",
    question: "What is the speaker's attitude toward the CFO's disclosure of the covenant waiver?",
    options: ["They consider it outright dishonest and a clear breach of the rules.", "They think it was fully transparent and beyond criticism.", "They regard it as narrowly within the rules yet ethically questionable.", "They believe the waiver should not have been disclosed at all."], correct_index: 2,
    explanation_en: "The speaker explicitly declines to call it dishonest but says burying it in a footnote strains the line between mere technical compliance and genuine openness, implying it is legal but not forthright.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "For all the fanfare around the merger, the synergies management promised have proven remarkably shy about materialising on the actual balance sheet.",
    question: "What is the speaker implying about the promised merger synergies?",
    options: ["They have appeared exactly as management forecast.", "They have largely failed to show up in the financial results.", "They were never publicly announced by management.", "They will certainly materialise given more time."], correct_index: 1,
    explanation_en: "The ironic phrase 'remarkably shy about materialising' means the synergies have not actually appeared in the figures despite being loudly promised.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "The auditor's report was less an endorsement than a carefully hedged refusal to condemn, which anyone who reads such things closely would recognise for what it is.",
    question: "How does the speaker characterise the auditor's report?",
    options: ["As a strong and unambiguous endorsement of the company.", "As an outright condemnation of the company's practices.", "As a guarded statement that stops just short of criticism rather than genuinely approving.", "As a routine document with no discernible stance."], correct_index: 2,
    explanation_en: "'Less an endorsement than a carefully hedged refusal to condemn' signals the report withholds real approval while avoiding open criticism - a cautious middle position.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "She has this knack of agreeing with every objection in the room and somehow leaving with precisely the mandate she walked in wanting.",
    question: "What does the speaker suggest about the woman?",
    options: ["She abandons her own position whenever she meets resistance.", "She skilfully appears accommodating while still getting her own way.", "She tends to alienate colleagues by dismissing their objections.", "She rarely enters meetings with any clear agenda."], correct_index: 1,
    explanation_en: "Appearing to agree with every objection yet leaving with exactly the mandate she wanted describes someone adept at seeming conciliatory while achieving her aims.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "The consultant's recommendations were impeccable in the abstract and almost entirely useless the moment they brushed up against how the department actually operates.",
    question: "What is the speaker's main point about the consultant's recommendations?",
    options: ["They were flawed in principle but worked well in practice.", "They were sound in theory yet impractical given real working conditions.", "They were both well-conceived and effectively implemented.", "They were rejected before anyone could evaluate them."], correct_index: 1,
    explanation_en: "'Impeccable in the abstract' but 'almost entirely useless' once they meet actual operations contrasts theoretical soundness with practical failure.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "I wouldn't go so far as to say the forecast was fabricated, but the assumptions underpinning it were chosen with an optimism bordering on the heroic.",
    question: "What is the speaker suggesting about the forecast?",
    options: ["It was deliberately falsified with invented figures.", "It rested on assumptions that were implausibly favourable, though not fraudulent.", "It was built on unusually conservative and cautious assumptions.", "It was entirely reasonable and free of any bias."], correct_index: 1,
    explanation_en: "The speaker rules out fabrication but says the assumptions were chosen with 'optimism bordering on the heroic', meaning unrealistically rosy rather than dishonest.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "Everyone keeps praising the treasurer's prudence, though if you ask me, what passes for prudence here is really just an unwillingness to make a decision that could ever be pinned on him.",
    question: "What is the speaker's view of the treasurer's so-called prudence?",
    options: ["It is genuine caution that has served the organisation well.", "It is really risk-averse indecision motivated by avoiding personal blame.", "It reflects a deliberate strategy agreed with the wider board.", "It shows a reckless disregard for the organisation's exposure."], correct_index: 1,
    explanation_en: "The speaker reframes the admired 'prudence' as a reluctance to make any decision that could be blamed on him, implying self-protective indecision rather than sound judgement.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "Our new compliance officer is nothing if not thorough, though some colleagues have begun to mutter that thoroughness and paralysis are starting to look suspiciously alike.",
    question: "What criticism of the compliance officer is being conveyed?",
    options: ["That the officer is careless and overlooks important details.", "That the officer's exhaustive caution is beginning to stall progress.", "That the officer lacks the expertise the role requires.", "That colleagues universally admire the officer's efficiency."], correct_index: 1,
    explanation_en: "Colleagues muttering that 'thoroughness and paralysis look suspiciously alike' suggests the officer's meticulousness is now impeding action - a veiled criticism.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "The board didn't reject the proposal outright; they simply referred it for further study, which in this organisation is a rather more polite way of burying it.",
    question: "What does the speaker imply about referring the proposal for further study?",
    options: ["It reflects genuine enthusiasm to develop the proposal further.", "It is effectively a diplomatic way of killing the proposal.", "It means the proposal will be approved after minor revisions.", "It indicates the board lacked the information to decide."], correct_index: 1,
    explanation_en: "'A rather more polite way of burying it' reveals that referral for further study functions as a face-saving means of quietly ending the proposal.",
  },
  {
    skill: "listening", cefr: "C2",
    content: "To be fair to the vendor, they delivered exactly what the contract specified - which was, unfortunately, nowhere near what anybody in the room had actually needed.",
    question: "Where does the speaker locate the source of the problem?",
    options: ["In the vendor's failure to honour the contract terms.", "In a poorly drafted contract that misstated the real requirements.", "In the vendor secretly overcharging for the delivered work.", "In the team's refusal to accept a satisfactory deliverable."], correct_index: 1,
    explanation_en: "Since the vendor delivered exactly what the contract specified yet it was not what anyone needed, the fault lies with the contract's specification, not the vendor's performance.",
  },
];
